// This file is automatically generated by i18next-cli. Do not edit manually.
export default interface Resources {
  "admin": {
    "app": {
      "title": "SuperDL 管理控制台"
    },
    "audit": {
      "actorAdmin": "管理员",
      "actorAnonymous": "匿名",
      "actorTypePlaceholder": "操作者类型",
      "actorUser": "用户",
      "colAction": "动作",
      "colActor": "操作者",
      "colResult": "结果",
      "colTarget": "目标",
      "colTime": "时间"
    },
    "common": {
      "actionDone": "{{action}}已执行",
      "actionFailed": "{{action}}失败",
      "backOverview": "回总览",
      "confirmExecute": "确认执行",
      "next": "下一步",
      "reasonLabel": "操作原因(必填,入审计)",
      "reasonPlaceholder": "原因将写入审计日志",
      "reasonRule": "请填写至少 2 个字的原因",
      "requestFailed": "请求失败",
      "retry": "重试",
      "secondConfirm": "二次确认"
    },
    "errorPage": {
      "title": "页面出错了",
      "unknown": "发生未知错误"
    },
    "lang": {
      "en": "English",
      "zh": "中文"
    },
    "login": {
      "failed": "登录失败",
      "isolatedNote": "管理端账号体系与用户端完全隔离,由平台管理员分配。",
      "password": "密码",
      "submit": "登录",
      "username": "用户名"
    },
    "menu": {
      "audit": "审计日志",
      "finance": "财务对账",
      "images": "镜像与预热",
      "nodes": "节点与 GPU",
      "overview": "运营总览",
      "platform": "平台配置",
      "settings": "系统设置",
      "skus": "SKU 与定价",
      "tenants": "租户与实例"
    },
    "notFound": {
      "title": "页面不存在"
    },
    "roles": {
      "admin": "超级管理员",
      "finance": "财务",
      "ops": "运维",
      "readonly": "只读"
    },
    "shell": {
      "alertsTitle": "告警流",
      "envDev": "预发/开发",
      "envProd": "生产环境",
      "logout": "退出登录",
      "noAlerts": "暂无告警"
    }
  },
  "errors": {
    "account": {
      "credentialRequired": "需提供验证码或密码",
      "loginFailed": "手机号或凭证错误",
      "loginFailedPassword": "手机号或密码错误",
      "loginFailedSms": "手机号或验证码错误",
      "phoneTaken": "该手机号已注册,请直接登录",
      "realNameChannelError": "实名核验服务暂不可用,请稍后重试",
      "realNameDone": "已完成实名认证,无需重复提交",
      "realNameMismatch": "实名信息与运营商记录不一致,请核对后重试",
      "smsCodeInvalid": "验证码错误或已过期",
      "smsSendFailed": "短信发送失败,请稍后重试",
      "smsTooFrequent": "发送过于频繁,请 {{seconds}} 秒后再试",
      "sshKeyDuplicate": "该公钥已添加过",
      "termsNotAccepted": "请先阅读并同意《用户协议》与《隐私政策》",
      "userFrozen": "账号已被冻结,请联系客服"
    },
    "adminapi": {
      "adjustAlreadyProcessed": "调账单已处理",
      "adjustNotZero": "调账金额不能为 0",
      "adjustSecondReviewer": "调账必须由第二位管理员复核",
      "badDayFormat": "day 格式应为 YYYY-MM-DD",
      "loginFailed": "用户名或密码错误",
      "smsTestFailed": "发送失败:{{message}}",
      "taskNotFound": "任务不存在",
      "taskStateNotIgnorable": "任务状态 {{status}} 不可忽略",
      "taskStateNotReplayable": "任务状态 {{status}} 不可重放",
      "userDisabled": "账号已停用"
    },
    "billing": {
      "alipayCallbackVerifyFailed": "支付宝回调验签失败",
      "alipayCreateFailed": "支付宝下单失败:{{message}}",
      "alipayCredentialsIncomplete": "支付宝商户凭据不完整(管理端·平台配置)",
      "alipayQueryFailed": "支付宝查单失败:{{message}}",
      "amountMismatchAdjust": "渠道金额 {{channel}} 与订单金额 {{order}} 不符,需人工调账处理",
      "badDateFormat": "日期格式应为 YYYY-MM-DD",
      "badMonthFormat": "月份格式应为 YYYY-MM",
      "callbackAmountMismatch": "回调金额与订单不符",
      "callbackChannelMismatch": "回调渠道与订单不符",
      "channelNotEnabled": "该支付渠道暂未开通,请选择其他支付方式",
      "channelStateNotBackfillable": "渠道侧状态为 {{status}},不能补单",
      "insufficientBalance": "余额不足,请先充值",
      "insufficientForDisk": "余额不足:新建数据盘需要至少 1 日费用 ¥{{amount}}",
      "insufficientForRestart": "余额不足:重启需要至少 1 小时预估费用",
      "insufficientForStart": "余额不足:开机需要至少 1 小时预估费用 ¥{{amount}}",
      "mockCallbackParseFailed": "mock 回调解析失败",
      "mockDevOnly": "mock 渠道仅限开发环境",
      "orderAlreadyPaid": "订单已入账,无需补单",
      "orderNotFound": "订单不存在",
      "orderStateNotBackfillable": "订单状态 {{status}} 不可补单",
      "realNameRequiredForRecharge": "按监管要求,充值前需完成实名认证",
      "rechargeAmountRange": "充值金额须在 {{min}}~{{max}} 元之间",
      "unknownChannel": "未知支付渠道:{{name}}",
      "wechatCallbackVerifyFailed": "微信回调验签失败",
      "wechatCreateFailed": "微信下单失败:{{message}}",
      "wechatCredentialsIncomplete": "微信支付商户凭据不完整(管理端·平台配置)",
      "wechatPublicKeyPair": "微信支付公钥模式需同时配置公钥与公钥 ID",
      "wechatQueryFailed": "微信查单失败:{{message}}"
    },
    "catalog": {
      "imageRefExists": "镜像 image_ref 已存在",
      "prewarmDisabled": "该镜像已关闭预热,请先开启",
      "skuOffSale": "该规格已下架"
    },
    "common": {
      "badCursor": "无效的分页游标",
      "forbidden": "无权访问",
      "internal": "服务器内部错误,请稍后重试",
      "notFound": "资源不存在",
      "rateLimited": "尝试过于频繁,请稍后再试",
      "unauthorized": "未登录或凭证已过期",
      "validation": "参数校验失败"
    },
    "disks": {
      "expandNeedsActive": "仅正常状态的数据盘可以扩容",
      "inUseDelete": "数据盘挂载中,请先释放对应实例",
      "mountedElsewhere": "数据盘已挂载到其他实例",
      "notMountable": "数据盘当前状态不可挂载",
      "shrinkForbidden": "数据盘只支持扩容,不支持缩容",
      "sizeMax": "容量上限 {{max}} GB",
      "sizeRange": "容量须在 {{min}}~{{max}} GB 之间"
    },
    "metering": {
      "badRange": "range 须为 1h/6h/24h",
      "unavailable": "监控数据暂不可用,不影响计费(计费依据为实例事件流水)"
    },
    "nodes": {
      "alreadyTerminal": "状态 {{status}} 已是终态,无需吊销",
      "clusterNotConfigured": "集群接入参数未配置:请超管在「平台配置 · 集群接入」录入 RKE2 Server 地址与 join token",
      "enrollTransition": "注册状态不允许 {{from}} → {{to}}",
      "hostnameMismatch": "主机名与登记不符,令牌已作废,请在管理端核对后重新生成",
      "regenerateNotAllowed": "状态 {{status}} 不允许重新生成(仅 待执行/已过期/已失败)"
    },
    "orchestrator": {
      "accessNeedsRunning": "实例运行中才能获取接入信息",
      "forceStopNeedsRunning": "仅运行中的实例可以强制停止",
      "frozenNeedsRecharge": "实例已因欠费冻结,充值解冻后可开机",
      "gpuCountRange": "GPU 数量须在 1~{{max}} 之间",
      "gpuQuota": "GPU 总数将超过上限({{max}} 卡),请释放后再创建或联系客服提额",
      "instanceQuota": "实例数已达上限({{max}} 台),请释放后再创建或联系客服提额",
      "invalidTransition": "实例当前状态({{from}})不允许该操作",
      "releaseNeedsStopped": "关机后才能释放实例",
      "restartNeedsRunning": "仅运行中的实例可以重启",
      "sshKeyRequired": "请至少选择一个 SSH 公钥(实例仅支持密钥登录)",
      "sshPortsExhausted": "当前无可分配的 SSH 端口,请稍后重试或联系客服",
      "startNeedsStopped": "仅已关机的实例可以开机",
      "stateChangedRetry": "实例状态已被其他操作变更,请刷新后重试",
      "stopNeedsRunning": "仅运行中的实例可以关机"
    }
  },
  "shared": {
    "format": {
      "countdown": {
        "expired": "已到期",
        "hours": "剩 {{count}}h",
        "minutes": "剩 {{count}}m",
        "reclaimHours": "剩 {{count}}h后回收",
        "reclaimMinutes": "剩 {{count}}m后回收",
        "reclaimNow": "即将回收"
      },
      "daysLeft": {
        "count": "剩 {{count}} 天",
        "dueToday": "今日到期",
        "expired": "已到期"
      },
      "duration": {
        "h": "{{h}} 小时",
        "hm": "{{h}} 小时 {{m}} 分",
        "lessThanMinute": "不足 1 分钟",
        "m": "{{m}} 分钟",
        "zero": "0 分钟"
      },
      "perHour": "{{price}}/时"
    },
    "status": {
      "disk": {
        "active": "正常",
        "deleted": "已清除",
        "deleting": "清除中",
        "frozen": "已冻结",
        "grace": "宽限期"
      },
      "imageCache": {
        "cached": "已缓存",
        "failed": "拉取失败",
        "pending": "待预热",
        "pulling": "拉取中"
      },
      "instance": {
        "creating": "创建中",
        "failed": "已失败",
        "frozen": "已冻结",
        "released": "已释放",
        "releasing": "释放中",
        "running": "运行中",
        "starting": "启动中",
        "stopped": "已关机",
        "stopping": "关机中"
      },
      "nodeEnroll": {
        "expired": "已过期",
        "failed": "已失败",
        "installing": "安装中",
        "joined": "已加入",
        "joining": "加入中",
        "pending": "待执行",
        "rebooting": "重启中",
        "revoked": "已吊销"
      },
      "tier": {
        "dedicated": "独享整卡",
        "mig": "MIG 切分",
        "shared_eco": "共享·经济",
        "shared_std": "共享·标准"
      },
      "tierHint": {
        "shared_eco": "性能可能波动"
      }
    }
  }
}
