cilium: {enabled: true}
gpuOperator: {enabled: true}
hami: {enabled: true}
kataDeploy: {enabled: true}
kps: {enabled: true}
topolvm: {enabled: true}
rookCeph: {enabled: true}
certManager: {enabled: true}
acmeDns: {enabled: true}
envoyGateway: {enabled: true}
cnpg: {enabled: true}
loki: {enabled: true}
logCollector: {enabled: true}
