/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ConsoleRouteImport } from './routes/_console'
import { Route as HelpRouteImport } from './routes/help'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ConsoleBillingRouteImport } from './routes/_console.billing'
import { Route as ConsoleDashboardRouteImport } from './routes/_console.dashboard'
import { Route as ConsoleInstancesRouteImport } from './routes/_console.instances'
import { Route as ConsoleMarketRouteImport } from './routes/_console.market'
import { Route as ConsoleSettingsRouteImport } from './routes/_console.settings'
import { Route as ConsoleStorageRouteImport } from './routes/_console.storage'
import { Route as LegalPrivacyRouteImport } from './routes/legal.privacy'
import { Route as LegalTermsRouteImport } from './routes/legal.terms'
import { Route as ConsoleInstancesUuidRouteImport } from './routes/_console.instances_.$uuid'
import { Route as ConsoleMarketCreateSkuIdRouteImport } from './routes/_console.market_.create.$skuId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ConsoleRoute = ConsoleRouteImport.update({
  id: '/_console',
  getParentRoute: () => rootRouteImport,
} as any)
const HelpRoute = HelpRouteImport.update({
  id: '/help',
  path: '/help',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ConsoleBillingRoute = ConsoleBillingRouteImport.update({
  id: '/billing',
  path: '/billing',
  getParentRoute: () => ConsoleRoute,
} as any)
const ConsoleDashboardRoute = ConsoleDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => ConsoleRoute,
} as any)
const ConsoleInstancesRoute = ConsoleInstancesRouteImport.update({
  id: '/instances',
  path: '/instances',
  getParentRoute: () => ConsoleRoute,
} as any)
const ConsoleMarketRoute = ConsoleMarketRouteImport.update({
  id: '/market',
  path: '/market',
  getParentRoute: () => ConsoleRoute,
} as any)
const ConsoleSettingsRoute = ConsoleSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => ConsoleRoute,
} as any)
const ConsoleStorageRoute = ConsoleStorageRouteImport.update({
  id: '/storage',
  path: '/storage',
  getParentRoute: () => ConsoleRoute,
} as any)
const LegalPrivacyRoute = LegalPrivacyRouteImport.update({
  id: '/legal/privacy',
  path: '/legal/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const LegalTermsRoute = LegalTermsRouteImport.update({
  id: '/legal/terms',
  path: '/legal/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const ConsoleInstancesUuidRoute = ConsoleInstancesUuidRouteImport.update({
  id: '/instances_/$uuid',
  path: '/instances/$uuid',
  getParentRoute: () => ConsoleRoute,
} as any)
const ConsoleMarketCreateSkuIdRoute =
  ConsoleMarketCreateSkuIdRouteImport.update({
    id: '/market_/create/$skuId',
    path: '/market/create/$skuId',
    getParentRoute: () => ConsoleRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/help': typeof HelpRoute
  '/login': typeof LoginRoute
  '/billing': typeof ConsoleBillingRoute
  '/dashboard': typeof ConsoleDashboardRoute
  '/instances': typeof ConsoleInstancesRoute
  '/market': typeof ConsoleMarketRoute
  '/settings': typeof ConsoleSettingsRoute
  '/storage': typeof ConsoleStorageRoute
  '/legal/privacy': typeof LegalPrivacyRoute
  '/legal/terms': typeof LegalTermsRoute
  '/instances/$uuid': typeof ConsoleInstancesUuidRoute
  '/market/create/$skuId': typeof ConsoleMarketCreateSkuIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/help': typeof HelpRoute
  '/login': typeof LoginRoute
  '/billing': typeof ConsoleBillingRoute
  '/dashboard': typeof ConsoleDashboardRoute
  '/instances': typeof ConsoleInstancesRoute
  '/market': typeof ConsoleMarketRoute
  '/settings': typeof ConsoleSettingsRoute
  '/storage': typeof ConsoleStorageRoute
  '/legal/privacy': typeof LegalPrivacyRoute
  '/legal/terms': typeof LegalTermsRoute
  '/instances/$uuid': typeof ConsoleInstancesUuidRoute
  '/market/create/$skuId': typeof ConsoleMarketCreateSkuIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_console': typeof ConsoleRouteWithChildren
  '/help': typeof HelpRoute
  '/login': typeof LoginRoute
  '/_console/billing': typeof ConsoleBillingRoute
  '/_console/dashboard': typeof ConsoleDashboardRoute
  '/_console/instances': typeof ConsoleInstancesRoute
  '/_console/market': typeof ConsoleMarketRoute
  '/_console/settings': typeof ConsoleSettingsRoute
  '/_console/storage': typeof ConsoleStorageRoute
  '/legal/privacy': typeof LegalPrivacyRoute
  '/legal/terms': typeof LegalTermsRoute
  '/_console/instances_/$uuid': typeof ConsoleInstancesUuidRoute
  '/_console/market_/create/$skuId': typeof ConsoleMarketCreateSkuIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/help'
    | '/login'
    | '/billing'
    | '/dashboard'
    | '/instances'
    | '/market'
    | '/settings'
    | '/storage'
    | '/legal/privacy'
    | '/legal/terms'
    | '/instances/$uuid'
    | '/market/create/$skuId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/help'
    | '/login'
    | '/billing'
    | '/dashboard'
    | '/instances'
    | '/market'
    | '/settings'
    | '/storage'
    | '/legal/privacy'
    | '/legal/terms'
    | '/instances/$uuid'
    | '/market/create/$skuId'
  id:
    | '__root__'
    | '/'
    | '/_console'
    | '/help'
    | '/login'
    | '/_console/billing'
    | '/_console/dashboard'
    | '/_console/instances'
    | '/_console/market'
    | '/_console/settings'
    | '/_console/storage'
    | '/legal/privacy'
    | '/legal/terms'
    | '/_console/instances_/$uuid'
    | '/_console/market_/create/$skuId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ConsoleRoute: typeof ConsoleRouteWithChildren
  HelpRoute: typeof HelpRoute
  LoginRoute: typeof LoginRoute
  LegalPrivacyRoute: typeof LegalPrivacyRoute
  LegalTermsRoute: typeof LegalTermsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_console': {
      id: '/_console'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof ConsoleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/help': {
      id: '/help'
      path: '/help'
      fullPath: '/help'
      preLoaderRoute: typeof HelpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_console/billing': {
      id: '/_console/billing'
      path: '/billing'
      fullPath: '/billing'
      preLoaderRoute: typeof ConsoleBillingRouteImport
      parentRoute: typeof ConsoleRoute
    }
    '/_console/dashboard': {
      id: '/_console/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof ConsoleDashboardRouteImport
      parentRoute: typeof ConsoleRoute
    }
    '/_console/instances': {
      id: '/_console/instances'
      path: '/instances'
      fullPath: '/instances'
      preLoaderRoute: typeof ConsoleInstancesRouteImport
      parentRoute: typeof ConsoleRoute
    }
    '/_console/market': {
      id: '/_console/market'
      path: '/market'
      fullPath: '/market'
      preLoaderRoute: typeof ConsoleMarketRouteImport
      parentRoute: typeof ConsoleRoute
    }
    '/_console/settings': {
      id: '/_console/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof ConsoleSettingsRouteImport
      parentRoute: typeof ConsoleRoute
    }
    '/_console/storage': {
      id: '/_console/storage'
      path: '/storage'
      fullPath: '/storage'
      preLoaderRoute: typeof ConsoleStorageRouteImport
      parentRoute: typeof ConsoleRoute
    }
    '/legal/privacy': {
      id: '/legal/privacy'
      path: '/legal/privacy'
      fullPath: '/legal/privacy'
      preLoaderRoute: typeof LegalPrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/legal/terms': {
      id: '/legal/terms'
      path: '/legal/terms'
      fullPath: '/legal/terms'
      preLoaderRoute: typeof LegalTermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_console/instances_/$uuid': {
      id: '/_console/instances_/$uuid'
      path: '/instances/$uuid'
      fullPath: '/instances/$uuid'
      preLoaderRoute: typeof ConsoleInstancesUuidRouteImport
      parentRoute: typeof ConsoleRoute
    }
    '/_console/market_/create/$skuId': {
      id: '/_console/market_/create/$skuId'
      path: '/market/create/$skuId'
      fullPath: '/market/create/$skuId'
      preLoaderRoute: typeof ConsoleMarketCreateSkuIdRouteImport
      parentRoute: typeof ConsoleRoute
    }
  }
}

interface ConsoleRouteChildren {
  ConsoleBillingRoute: typeof ConsoleBillingRoute
  ConsoleDashboardRoute: typeof ConsoleDashboardRoute
  ConsoleInstancesRoute: typeof ConsoleInstancesRoute
  ConsoleMarketRoute: typeof ConsoleMarketRoute
  ConsoleSettingsRoute: typeof ConsoleSettingsRoute
  ConsoleStorageRoute: typeof ConsoleStorageRoute
  ConsoleInstancesUuidRoute: typeof ConsoleInstancesUuidRoute
  ConsoleMarketCreateSkuIdRoute: typeof ConsoleMarketCreateSkuIdRoute
}

const ConsoleRouteChildren: ConsoleRouteChildren = {
  ConsoleBillingRoute: ConsoleBillingRoute,
  ConsoleDashboardRoute: ConsoleDashboardRoute,
  ConsoleInstancesRoute: ConsoleInstancesRoute,
  ConsoleMarketRoute: ConsoleMarketRoute,
  ConsoleSettingsRoute: ConsoleSettingsRoute,
  ConsoleStorageRoute: ConsoleStorageRoute,
  ConsoleInstancesUuidRoute: ConsoleInstancesUuidRoute,
  ConsoleMarketCreateSkuIdRoute: ConsoleMarketCreateSkuIdRoute,
}

const ConsoleRouteWithChildren =
  ConsoleRoute._addFileChildren(ConsoleRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ConsoleRoute: ConsoleRouteWithChildren,
  HelpRoute: HelpRoute,
  LoginRoute: LoginRoute,
  LegalPrivacyRoute: LegalPrivacyRoute,
  LegalTermsRoute: LegalTermsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
