operatorConfig:
  create: true
  driverSpecDefaults:
    imageSet:
      name: rook-csi-operator-image-set-configmap
    nodePlugin:
      priorityClassName: system-node-critical
    cephFsClientType: kernel

drivers:
  cephfs:
    enabled: true
    name: rook-ceph.cephfs.csi.ceph.com
    cephFsClientType: kernel
  rbd:
    enabled: false
  nfs:
    enabled: false
  nvmeof:
    enabled: false
