version:
  postgresql: "18"
cluster:
  instances: 3
  storage:
    size: 100Gi
    storageClass: topolvm-provisioner
  walStorage:
    enabled: true
    size: 20Gi
    storageClass: topolvm-provisioner
  resources:
    requests: {cpu: "1", memory: 4Gi}
    limits: {cpu: "1", memory: 4Gi}
  priorityClassName: system-cluster-critical
  monitoring:
    enabled: true
backups:
  enabled: true
  method: barmanObjectStore
  provider: s3
  endpointURL: "CHANGE_ME_S3_ENDPOINT"
  destinationPath: "s3://CHANGE_ME_BUCKET/cnpg"
  s3:
    region: "CHANGE_ME_S3_REGION"
    bucket: "CHANGE_ME_BUCKET"
    path: "/cnpg"
  secret:
    create: false
    name: cnpg-backup-s3
  wal:
    compression: gzip
    maxParallel: 2
  data:
    compression: gzip
  retentionPolicy: "30d"
  scheduledBackups:
    - name: daily-basebackup
      schedule: "0 30 18 * * *"
      method: barmanObjectStore
      backupOwnerReference: self
