driver:
  enabled: false
toolkit:
  enabled: true
devicePlugin:
  enabled: true
migManager:
  enabled: true
mig:
  strategy: mixed
dcgmExporter:
  enabled: true
  version: 4.6.0-4.8.3-distroless
  serviceMonitor:
    enabled: true
sandboxWorkloads:
  enabled: true
  mode: kata
vfioManager:
  enabled: true
