scheduler:
  defaultSchedulerPolicy:
    nodeSchedulerPolicy: binpack
    gpuSchedulerPolicy: binpack
devicePlugin:
  runtimeClassName: ""
  nvidiaNodeSelector:
    gpu: null
    superdl.io/pool: hami
devices:
  nvidia:
    gpuCorePolicy: force
