scheduler:
  defaultSchedulerPolicy:
    nodeSchedulerPolicy: binpack
    # 同卡尽量不放多个实例
    gpuSchedulerPolicy: spread
devicePlugin:
  runtimeClassName: ""
  nvidiaNodeSelector:
    gpu: null
    node-restriction.kubernetes.io/superdl-pool: hami
devices:
  nvidia:
    gpuCorePolicy: force
