nodeSelector:
  superdl.io/pool: kata

shims:
  disableAll: true
  qemu:
    enabled: true
    runtimeClass:
      nodeSelector:
        superdl.io/pool: kata
      overhead:
        memory: "512Mi"
        cpu: "250m"

runtimeClasses:
  enabled: true
  createDefault: false

node-feature-discovery:
  enabled: false
