nodeSelector:
  node-restriction.kubernetes.io/superdl-pool: kata

shims:
  disableAll: true
  qemu:
    enabled: true
    runtimeClass:
      nodeSelector:
        node-restriction.kubernetes.io/superdl-pool: kata
      overhead:
        memory: "512Mi"
        cpu: "250m"

runtimeClasses:
  enabled: true
  createDefault: false
