/** Every ITU-T E.164 country calling code offered by PhoneField; a code shared by several regions
 *  (+1, +7) appears once under its largest member. The server validates the E.164 shape and the
 *  compliance profile's region rule; this list only drives the picker. */

export interface DialCode {
  dial: string;
  iso: string;
}

export const DIAL_CODES: readonly DialCode[] = [
  { dial: "1", iso: "US" },
  { dial: "7", iso: "RU" },
  { dial: "20", iso: "EG" },
  { dial: "27", iso: "ZA" },
  { dial: "30", iso: "GR" },
  { dial: "31", iso: "NL" },
  { dial: "32", iso: "BE" },
  { dial: "33", iso: "FR" },
  { dial: "34", iso: "ES" },
  { dial: "36", iso: "HU" },
  { dial: "39", iso: "IT" },
  { dial: "40", iso: "RO" },
  { dial: "41", iso: "CH" },
  { dial: "43", iso: "AT" },
  { dial: "44", iso: "GB" },
  { dial: "45", iso: "DK" },
  { dial: "46", iso: "SE" },
  { dial: "47", iso: "NO" },
  { dial: "48", iso: "PL" },
  { dial: "49", iso: "DE" },
  { dial: "51", iso: "PE" },
  { dial: "52", iso: "MX" },
  { dial: "53", iso: "CU" },
  { dial: "54", iso: "AR" },
  { dial: "55", iso: "BR" },
  { dial: "56", iso: "CL" },
  { dial: "57", iso: "CO" },
  { dial: "58", iso: "VE" },
  { dial: "60", iso: "MY" },
  { dial: "61", iso: "AU" },
  { dial: "62", iso: "ID" },
  { dial: "63", iso: "PH" },
  { dial: "64", iso: "NZ" },
  { dial: "65", iso: "SG" },
  { dial: "66", iso: "TH" },
  { dial: "81", iso: "JP" },
  { dial: "82", iso: "KR" },
  { dial: "84", iso: "VN" },
  { dial: "86", iso: "CN" },
  { dial: "90", iso: "TR" },
  { dial: "91", iso: "IN" },
  { dial: "92", iso: "PK" },
  { dial: "93", iso: "AF" },
  { dial: "94", iso: "LK" },
  { dial: "95", iso: "MM" },
  { dial: "98", iso: "IR" },
  { dial: "211", iso: "SS" },
  { dial: "212", iso: "MA" },
  { dial: "213", iso: "DZ" },
  { dial: "216", iso: "TN" },
  { dial: "218", iso: "LY" },
  { dial: "220", iso: "GM" },
  { dial: "221", iso: "SN" },
  { dial: "222", iso: "MR" },
  { dial: "223", iso: "ML" },
  { dial: "224", iso: "GN" },
  { dial: "225", iso: "CI" },
  { dial: "226", iso: "BF" },
  { dial: "227", iso: "NE" },
  { dial: "228", iso: "TG" },
  { dial: "229", iso: "BJ" },
  { dial: "230", iso: "MU" },
  { dial: "231", iso: "LR" },
  { dial: "232", iso: "SL" },
  { dial: "233", iso: "GH" },
  { dial: "234", iso: "NG" },
  { dial: "235", iso: "TD" },
  { dial: "236", iso: "CF" },
  { dial: "237", iso: "CM" },
  { dial: "238", iso: "CV" },
  { dial: "239", iso: "ST" },
  { dial: "240", iso: "GQ" },
  { dial: "241", iso: "GA" },
  { dial: "242", iso: "CG" },
  { dial: "243", iso: "CD" },
  { dial: "244", iso: "AO" },
  { dial: "245", iso: "GW" },
  { dial: "246", iso: "IO" },
  { dial: "247", iso: "AC" },
  { dial: "248", iso: "SC" },
  { dial: "249", iso: "SD" },
  { dial: "250", iso: "RW" },
  { dial: "251", iso: "ET" },
  { dial: "252", iso: "SO" },
  { dial: "253", iso: "DJ" },
  { dial: "254", iso: "KE" },
  { dial: "255", iso: "TZ" },
  { dial: "256", iso: "UG" },
  { dial: "257", iso: "BI" },
  { dial: "258", iso: "MZ" },
  { dial: "260", iso: "ZM" },
  { dial: "261", iso: "MG" },
  { dial: "262", iso: "RE" },
  { dial: "263", iso: "ZW" },
  { dial: "264", iso: "NA" },
  { dial: "265", iso: "MW" },
  { dial: "266", iso: "LS" },
  { dial: "267", iso: "BW" },
  { dial: "268", iso: "SZ" },
  { dial: "269", iso: "KM" },
  { dial: "290", iso: "SH" },
  { dial: "291", iso: "ER" },
  { dial: "297", iso: "AW" },
  { dial: "298", iso: "FO" },
  { dial: "299", iso: "GL" },
  { dial: "350", iso: "GI" },
  { dial: "351", iso: "PT" },
  { dial: "352", iso: "LU" },
  { dial: "353", iso: "IE" },
  { dial: "354", iso: "IS" },
  { dial: "355", iso: "AL" },
  { dial: "356", iso: "MT" },
  { dial: "357", iso: "CY" },
  { dial: "358", iso: "FI" },
  { dial: "359", iso: "BG" },
  { dial: "370", iso: "LT" },
  { dial: "371", iso: "LV" },
  { dial: "372", iso: "EE" },
  { dial: "373", iso: "MD" },
  { dial: "374", iso: "AM" },
  { dial: "375", iso: "BY" },
  { dial: "376", iso: "AD" },
  { dial: "377", iso: "MC" },
  { dial: "378", iso: "SM" },
  { dial: "380", iso: "UA" },
  { dial: "381", iso: "RS" },
  { dial: "382", iso: "ME" },
  { dial: "383", iso: "XK" },
  { dial: "385", iso: "HR" },
  { dial: "386", iso: "SI" },
  { dial: "387", iso: "BA" },
  { dial: "389", iso: "MK" },
  { dial: "420", iso: "CZ" },
  { dial: "421", iso: "SK" },
  { dial: "423", iso: "LI" },
  { dial: "500", iso: "FK" },
  { dial: "501", iso: "BZ" },
  { dial: "502", iso: "GT" },
  { dial: "503", iso: "SV" },
  { dial: "504", iso: "HN" },
  { dial: "505", iso: "NI" },
  { dial: "506", iso: "CR" },
  { dial: "507", iso: "PA" },
  { dial: "508", iso: "PM" },
  { dial: "509", iso: "HT" },
  { dial: "590", iso: "GP" },
  { dial: "591", iso: "BO" },
  { dial: "592", iso: "GY" },
  { dial: "593", iso: "EC" },
  { dial: "594", iso: "GF" },
  { dial: "595", iso: "PY" },
  { dial: "596", iso: "MQ" },
  { dial: "597", iso: "SR" },
  { dial: "598", iso: "UY" },
  { dial: "599", iso: "CW" },
  { dial: "670", iso: "TL" },
  { dial: "672", iso: "NF" },
  { dial: "673", iso: "BN" },
  { dial: "674", iso: "NR" },
  { dial: "675", iso: "PG" },
  { dial: "676", iso: "TO" },
  { dial: "677", iso: "SB" },
  { dial: "678", iso: "VU" },
  { dial: "679", iso: "FJ" },
  { dial: "680", iso: "PW" },
  { dial: "681", iso: "WF" },
  { dial: "682", iso: "CK" },
  { dial: "683", iso: "NU" },
  { dial: "685", iso: "WS" },
  { dial: "686", iso: "KI" },
  { dial: "687", iso: "NC" },
  { dial: "688", iso: "TV" },
  { dial: "689", iso: "PF" },
  { dial: "690", iso: "TK" },
  { dial: "691", iso: "FM" },
  { dial: "692", iso: "MH" },
  { dial: "850", iso: "KP" },
  { dial: "852", iso: "HK" },
  { dial: "853", iso: "MO" },
  { dial: "855", iso: "KH" },
  { dial: "856", iso: "LA" },
  { dial: "880", iso: "BD" },
  { dial: "886", iso: "TW" },
  { dial: "960", iso: "MV" },
  { dial: "961", iso: "LB" },
  { dial: "962", iso: "JO" },
  { dial: "963", iso: "SY" },
  { dial: "964", iso: "IQ" },
  { dial: "965", iso: "KW" },
  { dial: "966", iso: "SA" },
  { dial: "967", iso: "YE" },
  { dial: "968", iso: "OM" },
  { dial: "970", iso: "PS" },
  { dial: "971", iso: "AE" },
  { dial: "972", iso: "IL" },
  { dial: "973", iso: "BH" },
  { dial: "974", iso: "QA" },
  { dial: "975", iso: "BT" },
  { dial: "976", iso: "MN" },
  { dial: "977", iso: "NP" },
  { dial: "992", iso: "TJ" },
  { dial: "993", iso: "TM" },
  { dial: "994", iso: "AZ" },
  { dial: "995", iso: "GE" },
  { dial: "996", iso: "KG" },
  { dial: "998", iso: "UZ" },
];

export const E164_RE = /^\+[1-9]\d{6,14}$/;

/** Split an E.164 value into the longest known dial code and the national part. */
export function splitE164(value: string): { dial: string; national: string } | null {
  if (!E164_RE.test(value)) return null;
  const digits = value.slice(1);
  const dial = [...DIAL_CODES]
    .map((d) => d.dial)
    .filter((d) => digits.startsWith(d))
    .sort((a, b) => b.length - a.length)[0];
  if (!dial) return null;
  return { dial, national: digits.slice(dial.length) };
}

/** Compose an E.164 value; returns null while the national part is empty or the result is invalid. */
export function composeE164(dial: string, national: string): string | null {
  const digits = national.replace(/\D/g, "");
  if (digits === "") return null;
  const value = `+${dial}${digits}`;
  return E164_RE.test(value) ? value : null;
}
