apiVersion: v1
kind: Namespace
metadata:
  name: topolvm-system
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: topolvm-lvm-config
  namespace: topolvm-system
  labels:
    superdl.io/managed: "true"
data:
  lvm.conf: |
    devices {
        issue_discards = 1
    }
