// This file is automatically generated by i18next-cli. Do not edit manually.
export default interface Resources {
  "shared": {
    "status": {
      "disk": {
        "active": "正常",
        "deleted": "已清除",
        "deleting": "清除中",
        "frozen": "已冻结",
        "grace": "宽限期"
      },
      "imageCache": {
        "cached": "已缓存",
        "failed": "拉取失败",
        "pending": "待预热",
        "pulling": "拉取中"
      },
      "instance": {
        "creating": "创建中",
        "failed": "已失败",
        "frozen": "已冻结",
        "released": "已释放",
        "releasing": "释放中",
        "running": "运行中",
        "starting": "启动中",
        "stopped": "已关机",
        "stopping": "关机中"
      },
      "nodeEnroll": {
        "expired": "已过期",
        "failed": "已失败",
        "installing": "安装中",
        "joined": "已加入",
        "joining": "加入中",
        "pending": "待执行",
        "rebooting": "重启中",
        "revoked": "已吊销"
      },
      "tier": {
        "dedicated": "独享整卡",
        "mig": "MIG 切分",
        "shared_eco": "共享·经济",
        "shared_std": "共享·标准"
      },
      "tierHint": {
        "shared_eco": "性能可能波动"
      }
    }
  },
  "web": {
    "app": {
      "title": "SuperDL · GPU 算力云"
    },
    "common": {
      "backConsole": "回控制台",
      "backHome": "回首页",
      "retry": "重试"
    },
    "errorPage": {
      "title": "页面出错了",
      "unknown": "发生未知错误,请重试或返回首页"
    },
    "lang": {
      "en": "English",
      "zh": "中文"
    },
    "notFound": {
      "subtitle": "你访问的地址不存在或已被移除",
      "title": "页面不存在"
    }
  }
}
