"""wp1 account tables

Revision ID: 459608e797b3
Revises: 9529712bb5de
Create Date: 2026-08-19 12:45:59.170672

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '459608e797b3'
down_revision: Union[str, None] = '9529712bb5de'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sms_codes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=False),
    sa.Column('code', sa.String(length=8), nullable=False),
    sa.Column('purpose', sa.String(length=16), nullable=False),
    sa.Column('expires_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('used_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_sms_codes'))
    )
    op.create_index(op.f('ix_sms_codes_phone'), 'sms_codes', ['phone'], unique=False)
    op.create_table('ssh_keys',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('public_key', sa.Text(), nullable=False),
    sa.Column('fingerprint', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_ssh_keys')),
    sa.UniqueConstraint('fingerprint', name=op.f('uq_ssh_keys_fingerprint'))
    )
    op.create_index(op.f('ix_ssh_keys_user_id'), 'ssh_keys', ['user_id'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=False),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('low_balance_warn_hours', sa.Integer(), nullable=False),
    sa.Column('id_name', sa.String(length=64), nullable=True),
    sa.Column('id_number', sa.String(length=32), nullable=True),
    sa.Column('company_name', sa.String(length=128), nullable=True),
    sa.Column('company_tax_id', sa.String(length=32), nullable=True),
    sa.Column('invoice_title', sa.String(length=128), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users')),
    sa.UniqueConstraint('phone', name=op.f('uq_users_phone'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users')
    op.drop_index(op.f('ix_ssh_keys_user_id'), table_name='ssh_keys')
    op.drop_table('ssh_keys')
    op.drop_index(op.f('ix_sms_codes_phone'), table_name='sms_codes')
    op.drop_table('sms_codes')
    # ### end Alembic commands ###
