"""wp11 admin adjustments

Revision ID: 271c4c44a161
Revises: 9c5ea5524d56
Create Date: 2026-08-19 13:29:47.092960

"""

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = "271c4c44a161"
down_revision: str | None = "9c5ea5524d56"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "admin_adjustments",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("amount", sa.Numeric(precision=14, scale=2), nullable=False),
        sa.Column("reason", sa.String(length=256), nullable=False),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("created_by", sa.Integer(), nullable=False),
        sa.Column("reviewed_by", sa.Integer(), nullable=True),
        sa.Column("review_comment", sa.String(length=256), nullable=True),
        sa.Column(
            "created_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("reviewed_at", sa.TIMESTAMP(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_admin_adjustments")),
    )
    op.create_index(
        op.f("ix_admin_adjustments_user_id"), "admin_adjustments", ["user_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_admin_adjustments_user_id"), table_name="admin_adjustments")
    op.drop_table("admin_adjustments")
    # ### end Alembic commands ###
