"""wp8 data disks

Revision ID: 5f88f0e48449
Revises: 475856bc70b3
Create Date: 2026-08-19 13:24:11.567039

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '5f88f0e48449'
down_revision: Union[str, None] = '475856bc70b3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('data_disks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uuid', sa.String(length=32), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('size_gb', sa.Integer(), nullable=False),
    sa.Column('juicefs_subpath', sa.String(length=128), nullable=False),
    sa.Column('price_gb_month', sa.Numeric(precision=12, scale=4), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('mounted_instance_id', sa.Integer(), nullable=True),
    sa.Column('grace_started_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('frozen_started_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_data_disks')),
    sa.UniqueConstraint('juicefs_subpath', name=op.f('uq_data_disks_juicefs_subpath')),
    sa.UniqueConstraint('uuid', name=op.f('uq_data_disks_uuid'))
    )
    op.create_index(op.f('ix_data_disks_mounted_instance_id'), 'data_disks', ['mounted_instance_id'], unique=False)
    op.create_index(op.f('ix_data_disks_status'), 'data_disks', ['status'], unique=False)
    op.create_index(op.f('ix_data_disks_user_id'), 'data_disks', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_data_disks_user_id'), table_name='data_disks')
    op.drop_index(op.f('ix_data_disks_status'), table_name='data_disks')
    op.drop_index(op.f('ix_data_disks_mounted_instance_id'), table_name='data_disks')
    op.drop_table('data_disks')
    # ### end Alembic commands ###
