"""money check constraints

Revision ID: 32de653d3d22
Revises: 423784ab059f
Create Date: 2026-08-21 22:41:53.179806

"""

from collections.abc import Sequence

from alembic import op


revision: str = "32de653d3d22"
down_revision: str | None = "423784ab059f"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """money 表的 DB 层兜底约束。

    应用层的口径本来就有(bill_amount 会对越界秒数 raise、as_amount 拒 float),这里补的是
    「手工 SQL / 未来新写入路径绕过应用层」那一档:让一次坏写在写入那一刻响亮地失败,
    而不是变成一行谁也解释不了的记录,等对账任务半天后才发现。

    刻意**不**加 wallets.balance >= 0 —— 透支是设计内的(服务已消费完才结算),
    加了会让合法的结算扣款整批失败。跨模块外键同样不加:CLAUDE.md 第 6 条禁止跨模块查表,
    加外键与那条架构约束相矛盾,收益也很小。

    全部是钱表:ADD CONSTRAINT 一律 NOT VALID 先行(不锁表校验存量),再独立
    VALIDATE CONSTRAINT(只持 SHARE UPDATE EXCLUSIVE,不阻塞读写)。
    """
    # (约束名, 表, 谓词)
    checks: tuple[tuple[str, str, str], ...] = (
        ("ck_balance_ledger_amount_nonzero", "balance_ledger", "amount <> 0"),
        ("ck_bills_daily_disk_amount_nonneg", "bills_daily_disk", "amount >= 0"),
        ("ck_bills_daily_disk_size_nonneg", "bills_daily_disk", "size_gb >= 0"),
        ("ck_bills_hourly_amount_nonneg", "bills_hourly", "amount >= 0"),
        (
            "ck_bills_hourly_seconds_range",
            "bills_hourly",
            "seconds_used >= 0 AND seconds_used <= 3600",
        ),
        ("ck_orders_amount_positive", "orders", "amount > 0"),
        ("ck_wallets_frozen_nonneg", "wallets", "frozen_amount >= 0"),
    )
    for name, table, predicate in checks:
        op.execute(f"ALTER TABLE {table} ADD CONSTRAINT {name} CHECK ({predicate}) NOT VALID")
    for name, table, _predicate in checks:
        op.execute(f"ALTER TABLE {table} VALIDATE CONSTRAINT {name}")


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f("ck_wallets_frozen_nonneg"), "wallets", type_="check")
    op.drop_constraint(op.f("ck_orders_amount_positive"), "orders", type_="check")
    op.drop_constraint(op.f("ck_bills_hourly_seconds_range"), "bills_hourly", type_="check")
    op.drop_constraint(op.f("ck_bills_hourly_amount_nonneg"), "bills_hourly", type_="check")
    op.drop_constraint(op.f("ck_bills_daily_disk_size_nonneg"), "bills_daily_disk", type_="check")
    op.drop_constraint(op.f("ck_bills_daily_disk_amount_nonneg"), "bills_daily_disk", type_="check")
    op.drop_constraint(op.f("ck_balance_ledger_amount_nonzero"), "balance_ledger", type_="check")
