"""wp3 orchestrator and billing base tables

Revision ID: ab685bad9a97
Revises: b5c41b34f7c7
Create Date: 2026-08-19 13:03:55.288041

"""

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = "ab685bad9a97"
down_revision: str | None = "b5c41b34f7c7"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "balance_ledger",
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("type", sa.String(length=16), nullable=False),
        sa.Column("amount", sa.Numeric(precision=14, scale=2), nullable=False),
        sa.Column("balance_after", sa.Numeric(precision=14, scale=2), nullable=False),
        sa.Column("ref_type", sa.String(length=32), nullable=True),
        sa.Column("ref_id", sa.String(length=64), nullable=True),
        sa.Column("remark", sa.String(length=256), nullable=True),
        sa.Column(
            "created_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_balance_ledger")),
    )
    op.create_index(
        op.f("ix_balance_ledger_created_at"), "balance_ledger", ["created_at"], unique=False
    )
    op.create_index(op.f("ix_balance_ledger_user_id"), "balance_ledger", ["user_id"], unique=False)
    op.create_table(
        "bills_daily_disk",
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.Column("disk_id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("day", sa.TIMESTAMP(timezone=True), nullable=False),
        sa.Column("size_gb", sa.Integer(), nullable=False),
        sa.Column("unit_price", sa.Numeric(precision=12, scale=4), nullable=False),
        sa.Column("amount", sa.Numeric(precision=14, scale=2), nullable=False),
        sa.Column(
            "created_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_bills_daily_disk")),
        sa.UniqueConstraint("disk_id", "day", name=op.f("uq_bills_daily_disk_disk_id_day")),
    )
    op.create_index(
        op.f("ix_bills_daily_disk_disk_id"), "bills_daily_disk", ["disk_id"], unique=False
    )
    op.create_index(
        op.f("ix_bills_daily_disk_user_id"), "bills_daily_disk", ["user_id"], unique=False
    )
    op.create_table(
        "bills_hourly",
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.Column("instance_id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("hour_start", sa.TIMESTAMP(timezone=True), nullable=False),
        sa.Column("seconds_used", sa.Integer(), nullable=False),
        sa.Column("unit_price", sa.Numeric(precision=12, scale=4), nullable=False),
        sa.Column("gpu_count", sa.Integer(), nullable=False),
        sa.Column("amount", sa.Numeric(precision=14, scale=2), nullable=False),
        sa.Column("detail", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column(
            "created_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_bills_hourly")),
        sa.UniqueConstraint(
            "instance_id", "hour_start", name=op.f("uq_bills_hourly_instance_id_hour_start")
        ),
    )
    op.create_index(
        op.f("ix_bills_hourly_hour_start"), "bills_hourly", ["hour_start"], unique=False
    )
    op.create_index(
        op.f("ix_bills_hourly_instance_id"), "bills_hourly", ["instance_id"], unique=False
    )
    op.create_index(op.f("ix_bills_hourly_user_id"), "bills_hourly", ["user_id"], unique=False)
    op.create_table(
        "instance_events",
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.Column("instance_id", sa.Integer(), nullable=False),
        sa.Column("from_status", sa.String(length=16), nullable=True),
        sa.Column("to_status", sa.String(length=16), nullable=False),
        sa.Column("reason", sa.String(length=64), nullable=False),
        sa.Column("actor", sa.String(length=16), nullable=False),
        sa.Column("metadata", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column(
            "created_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_instance_events")),
    )
    op.create_index(
        op.f("ix_instance_events_created_at"), "instance_events", ["created_at"], unique=False
    )
    op.create_index(
        op.f("ix_instance_events_instance_id"), "instance_events", ["instance_id"], unique=False
    )
    op.create_table(
        "instances",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("uuid", sa.String(length=32), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=64), nullable=False),
        sa.Column("sku_id", sa.Integer(), nullable=False),
        sa.Column("spec", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("price_hourly", sa.Numeric(precision=12, scale=4), nullable=False),
        sa.Column("gpu_count", sa.Integer(), nullable=False),
        sa.Column("image_ref", sa.String(length=256), nullable=False),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("k8s_namespace", sa.String(length=64), nullable=True),
        sa.Column("pod_name", sa.String(length=64), nullable=True),
        sa.Column("node_name", sa.String(length=64), nullable=True),
        sa.Column("ssh_port", sa.Integer(), nullable=True),
        sa.Column("jupyter_token", sa.String(length=64), nullable=False),
        sa.Column("authorized_keys", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("data_disk_id", sa.Integer(), nullable=True),
        sa.Column("idempotency_key", sa.String(length=64), nullable=True),
        sa.Column("frozen_deadline", sa.TIMESTAMP(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_instances")),
        sa.UniqueConstraint(
            "user_id", "idempotency_key", name=op.f("uq_instances_user_id_idempotency_key")
        ),
        sa.UniqueConstraint("uuid", name=op.f("uq_instances_uuid")),
    )
    op.create_index(op.f("ix_instances_status"), "instances", ["status"], unique=False)
    op.create_index(op.f("ix_instances_user_id"), "instances", ["user_id"], unique=False)
    op.create_table(
        "port_allocations",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("port", sa.Integer(), nullable=False),
        sa.Column("instance_id", sa.Integer(), nullable=True),
        sa.Column(
            "updated_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_port_allocations")),
        sa.UniqueConstraint("port", name=op.f("uq_port_allocations_port")),
    )
    op.create_index(
        op.f("ix_port_allocations_instance_id"), "port_allocations", ["instance_id"], unique=False
    )
    op.create_table(
        "wallets",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("balance", sa.Numeric(precision=14, scale=2), nullable=False),
        sa.Column("frozen_amount", sa.Numeric(precision=14, scale=2), nullable=False),
        sa.Column(
            "updated_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_wallets")),
        sa.UniqueConstraint("user_id", name=op.f("uq_wallets_user_id")),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("wallets")
    op.drop_index(op.f("ix_port_allocations_instance_id"), table_name="port_allocations")
    op.drop_table("port_allocations")
    op.drop_index(op.f("ix_instances_user_id"), table_name="instances")
    op.drop_index(op.f("ix_instances_status"), table_name="instances")
    op.drop_table("instances")
    op.drop_index(op.f("ix_instance_events_instance_id"), table_name="instance_events")
    op.drop_index(op.f("ix_instance_events_created_at"), table_name="instance_events")
    op.drop_table("instance_events")
    op.drop_index(op.f("ix_bills_hourly_user_id"), table_name="bills_hourly")
    op.drop_index(op.f("ix_bills_hourly_instance_id"), table_name="bills_hourly")
    op.drop_index(op.f("ix_bills_hourly_hour_start"), table_name="bills_hourly")
    op.drop_table("bills_hourly")
    op.drop_index(op.f("ix_bills_daily_disk_user_id"), table_name="bills_daily_disk")
    op.drop_index(op.f("ix_bills_daily_disk_disk_id"), table_name="bills_daily_disk")
    op.drop_table("bills_daily_disk")
    op.drop_index(op.f("ix_balance_ledger_user_id"), table_name="balance_ledger")
    op.drop_index(op.f("ix_balance_ledger_created_at"), table_name="balance_ledger")
    op.drop_table("balance_ledger")
    # ### end Alembic commands ###
