"""wp27_cluster_status

Revision ID: d00e1b8449b6
Revises: 6cef72d46b82
Create Date: 2026-08-21 12:28:18.574002

"""

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = "d00e1b8449b6"
down_revision: str | None = "6cef72d46b82"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "cluster_status",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("api_reachable", sa.Boolean(), nullable=False),
        sa.Column("k8s_version", sa.String(length=64), nullable=True),
        sa.Column("distro", sa.String(length=16), nullable=True),
        sa.Column("hami_ready", sa.Boolean(), nullable=False),
        sa.Column("dcgm_present", sa.Boolean(), nullable=False),
        sa.Column("kps_present", sa.Boolean(), nullable=False),
        sa.Column("gpu_operator_present", sa.Boolean(), nullable=False),
        sa.Column("kata_runtimeclass", sa.Boolean(), nullable=False),
        sa.Column("storage_classes", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("pools", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("detail", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("error", sa.Text(), nullable=True),
        sa.Column("probed_at", sa.TIMESTAMP(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_cluster_status")),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("cluster_status")
    # ### end Alembic commands ###
