"""wp2 catalog and admin tables

Revision ID: b5c41b34f7c7
Revises: 459608e797b3
Create Date: 2026-08-19 12:50:24.869119

"""

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = "b5c41b34f7c7"
down_revision: str | None = "459608e797b3"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "admin_users",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("username", sa.String(length=64), nullable=False),
        sa.Column("password_hash", sa.String(length=128), nullable=False),
        sa.Column("role", sa.String(length=16), nullable=False),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column(
            "created_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_admin_users")),
        sa.UniqueConstraint("username", name=op.f("uq_admin_users_username")),
    )
    op.create_table(
        "images",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("framework", sa.String(length=32), nullable=False),
        sa.Column("framework_version", sa.String(length=32), nullable=False),
        sa.Column("python_version", sa.String(length=16), nullable=False),
        sa.Column("cuda_version", sa.String(length=16), nullable=False),
        sa.Column("image_ref", sa.String(length=256), nullable=False),
        sa.Column("is_prewarmed", sa.Boolean(), nullable=False),
        sa.Column("sort", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_images")),
        sa.UniqueConstraint("image_ref", name=op.f("uq_images_image_ref")),
    )
    op.create_table(
        "skus",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=64), nullable=False),
        sa.Column("gpu_model", sa.String(length=32), nullable=False),
        sa.Column("tier", sa.String(length=16), nullable=False),
        sa.Column("mig_profile", sa.String(length=32), nullable=True),
        sa.Column("gpu_cores_pct", sa.Integer(), nullable=False),
        sa.Column("vram_gb", sa.Integer(), nullable=False),
        sa.Column("oversell_cores", sa.Numeric(precision=4, scale=2), nullable=False),
        sa.Column("oversell_vram", sa.Numeric(precision=4, scale=2), nullable=False),
        sa.Column("pool_label", sa.String(length=32), nullable=False),
        sa.Column("vcpu", sa.Integer(), nullable=False),
        sa.Column("mem_gb", sa.Integer(), nullable=False),
        sa.Column("disk_gb", sa.Integer(), nullable=False),
        sa.Column("price_hourly", sa.Numeric(precision=12, scale=4), nullable=False),
        sa.Column("max_gpus_per_instance", sa.Integer(), nullable=False),
        sa.Column("cuda_max", sa.String(length=16), nullable=True),
        sa.Column("status", sa.String(length=8), nullable=False),
        sa.Column(
            "created_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_skus")),
    )
    op.create_index(op.f("ix_skus_gpu_model"), "skus", ["gpu_model"], unique=False)
    op.create_index(op.f("ix_skus_status"), "skus", ["status"], unique=False)
    op.create_index(op.f("ix_skus_tier"), "skus", ["tier"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_skus_tier"), table_name="skus")
    op.drop_index(op.f("ix_skus_status"), table_name="skus")
    op.drop_index(op.f("ix_skus_gpu_model"), table_name="skus")
    op.drop_table("skus")
    op.drop_table("images")
    op.drop_table("admin_users")
    # ### end Alembic commands ###
