"""基线迁移:全量 schema(等价于既往迁移链终态)+ 必备预置数据。

预置数据(fresh DB 必需,seed 脚本不种):legal_doc_versions 三条 zh-CN published v1
(terms/privacy/deletion_notice,正文内联)与 port_allocations 的 30500 封禁行;
另设 rate_limit_counters / outbox_tasks 的 fillfactor(存储参数不入 metadata)。

Revision ID: 1620c05976ce
Revises:
Create Date: 2026-09-01 13:46:01.534141

"""

from collections.abc import Sequence
from datetime import UTC, datetime

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "1620c05976ce"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


TERMS_TITLE = "SuperDL 用户协议"
TERMS_MD = """\
## 一、服务说明

SuperDL(下称「本平台」)向用户提供 GPU 容器实例租赁与配套存储服务,按量计费、按秒累计、
账单可自查。实例创建、计费起止均以平台实例事件流水为准。

## 二、账号与实名

用户须以本人手机号注册,并根据《网络安全法》要求在使用付费功能前完成实名认证。账号仅限本人使用,因转借、出售账号造成的损失由用户自行承担。

## 三、使用限制

禁止利用本平台从事任何违法活动;明确禁止虚拟货币挖矿、网络攻击、流量代理等行为,一经发现平台有权立即停止服务并冻结账号,情节严重的将报告有关部门。

## 四、计费与退款

实例按秒累计、按小时出账;关机即停 GPU 计费,数据盘按日计费。创建失败不产生费用。
余额不足时实例将自动关机并进入冻结与回收流程,具体参数以「费用中心」公示为准。

## 五、数据与备份

数据盘在实例释放后独立保留;欠费超过公示宽限期后平台有权回收并删除数据。用户应自行对重要数据保留副本,平台对因用户欠费回收导致的数据损失不承担责任。

## 六、服务变更与终止

平台因维护、升级需要暂停服务的,将提前公告。用户可随时释放实例并申请余额处理。本协议未尽事宜以平台公告为准。"""

PRIVACY_TITLE = "SuperDL 隐私政策"
PRIVACY_MD = """\
## 一、我们收集的信息

注册与登录:手机号、登录 IP、设备信息;实名认证:姓名与身份证号(仅用于三要素核验,
身份证号只保存脱敏形态,不存储原文);服务使用:SSH 公钥、实例操作记录、账单与资金流水。

## 二、信息的使用

上述信息仅用于:身份核验与账号安全(登录风控、验证码)、计费与开票、依法配合监管要求。我们不会将您的个人信息用于本政策载明目的之外的用途,不向第三方出售个人信息。

## 三、信息的存储与保护

数据存储于中华人民共和国境内。密码以 bcrypt 加盐哈希存储;身份证号仅存脱敏串;
全部管理操作留存审计日志。我们采取访问控制、传输加密(TLS)等措施保护您的信息。

## 四、信息的保留与删除

账号注销后,法律法规要求留存的日志与交易记录(如资金流水)将按法定期限保留,其余个人信息将删除或匿名化。验证码等临时数据在过期后定期清除。

## 五、您的权利

您可以查询、更正个人信息,设置余额预警阈值,或联系平台申请注销账号。对个人信息处理有异议的,可通过页脚联系方式与我们联系。"""

DELETION_NOTICE_TITLE = "数据删除说明"
DELETION_NOTICE_MD = """\
账号注销前请完整阅读本说明。注销一经执行不可撤销。

## 一、资源清空

名下实例须全部释放、数据盘须全部删除,否则注销将被驳回。实例释放后其本地盘数据不可恢复,请提前备份。

## 二、余额处理

钱包余额须先经「费用中心 · 退款」流程提现,余额非零的账号将被自动驳回。
退款到账后方可重新提交注销申请。

## 三、身份匿名化

注销执行后,手机号与实名信息将被匿名化,注销后不可恢复;该手机号可重新注册为新账号,但原账号数据不再关联。

## 四、法定保留

账本与账单按法定义务保留,但不再关联您的身份信息;依法要求留存的日志与交易记录在法定期限届满后删除或匿名化。

## 五、冷静期

提交申请后进入 7 天冷静期,期间可随时撤销;冷静期届满由管理员审核执行。"""


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "account_deletion_requests",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("reason", sa.String(length=256), nullable=False),
        sa.Column(
            "requested_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("processed_by", sa.Integer(), nullable=True),
        sa.Column("processed_at", sa.TIMESTAMP(timezone=True), nullable=True),
        sa.Column("note", sa.String(length=512), nullable=True),
        sa.CheckConstraint(
            "status IN ('pending', 'completed', 'rejected', 'cancelled')",
            name=op.f("ck_account_deletion_requests_status"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_account_deletion_requests")),
    )
    op.create_index(
        op.f("ix_account_deletion_requests_status"),
        "account_deletion_requests",
        ["status"],
        unique=False,
    )
    op.create_index(
        op.f("ix_account_deletion_requests_user_id"),
        "account_deletion_requests",
        ["user_id"],
        unique=False,
    )
    op.create_index(
        "uq_account_deletion_requests_pending_user",
        "account_deletion_requests",
        ["user_id"],
        unique=True,
        postgresql_where=sa.text("status = 'pending'"),
    )
    op.create_table(
        "admin_adjustments",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("amount", sa.Numeric(precision=14, scale=2), nullable=False),
        sa.Column("reason", sa.String(length=256), nullable=False),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("created_by", sa.Integer(), nullable=False),
        sa.Column("reviewed_by", sa.Integer(), nullable=True),
        sa.Column("review_comment", sa.String(length=256), nullable=True),
        sa.Column("idempotency_key", sa.String(length=64), nullable=True),
        sa.Column("request_fingerprint", sa.String(length=64), nullable=True),
        sa.Column(
            "created_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("reviewed_at", sa.TIMESTAMP(timezone=True), nullable=True),
        sa.CheckConstraint(
            "status IN ('pending', 'approved', 'rejected')",
            name=op.f("ck_admin_adjustments_status"),
        ),
        sa.CheckConstraint("amount <> 0", name=op.f("ck_admin_adjustments_amount_nonzero")),
        sa.CheckConstraint(
            "reviewed_by IS NULL OR reviewed_by <> created_by",
            name=op.f("ck_admin_adjustments_reviewer_not_creator"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_admin_adjustments")),
        sa.UniqueConstraint(
            "created_by", "user_id", "idempotency_key", name="uq_admin_adjustments_idem_scope"
        ),
    )
    op.create_index(
        op.f("ix_admin_adjustments_user_id"), "admin_adjustments", ["user_id"], unique=False
    )
    op.create_table(
        "admin_users",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("username", sa.String(length=64), nullable=False),
        sa.Column("password_hash", sa.String(length=128), nullable=False),
        sa.Column("role", sa.String(length=16), nullable=False),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("token_version", sa.Integer(), server_default="0", nullable=False),
        sa.Column("totp_secret", sa.String(length=255), nullable=True),
        sa.Column("totp_enabled", sa.Boolean(), server_default="false", nullable=False),
        sa.Column("totp_recovery", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("last_totp_timestep", sa.BigInteger(), nullable=True),
        sa.Column(
            "created_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_admin_users")),
        sa.UniqueConstraint("username", name=op.f("uq_admin_users_username")),
    )
    op.create_table(
        "announcements",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("title", sa.String(length=128), nullable=False),
        sa.Column("content", sa.Text(), nullable=False),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("reached", sa.Integer(), nullable=False),
        sa.Column("created_by", sa.Integer(), nullable=False),
        sa.Column("idempotency_key", sa.String(length=64), nullable=True),
        sa.Column(
            "created_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("revoked_by", sa.Integer(), nullable=True),
        sa.Column("revoked_at", sa.TIMESTAMP(timezone=True), nullable=True),
        sa.Column("revoke_reason", sa.String(length=256), nullable=True),
        sa.CheckConstraint(
            "status IN ('published', 'revoked')", name=op.f("ck_announcements_status")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_announcements")),
        sa.UniqueConstraint("idempotency_key", name=op.f("uq_announcements_idempotency_key")),
    )
    op.create_table(
        "audit_log",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("actor_type", sa.String(length=16), nullable=False),
        sa.Column("actor_id", sa.String(length=64), nullable=True),
        sa.Column("action", sa.String(length=128), nullable=False),
        sa.Column("target", sa.String(length=256), nullable=True),
        sa.Column("ip", postgresql.INET(), nullable=True),
        sa.Column("result", sa.Integer(), nullable=False),
        sa.Column("detail", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("request_id", sa.String(length=64), nullable=True),
        sa.Column("user_agent", sa.String(length=256), nullable=True),
        sa.Column(
            "created_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_audit_log")),
    )
    op.create_index(op.f("ix_audit_log_action"), "audit_log", ["action"], unique=False)
    op.create_index("ix_audit_log_actor_id_id", "audit_log", ["actor_id", "id"], unique=False)
    op.create_index(op.f("ix_audit_log_created_at"), "audit_log", ["created_at"], unique=False)
    op.create_table(
        "balance_ledger",
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("type", sa.String(length=16), nullable=False),
        sa.Column("amount", sa.Numeric(precision=14, scale=2), nullable=False),
        sa.Column("balance_after", sa.Numeric(precision=14, scale=2), nullable=False),
        sa.Column("ref_type", sa.String(length=32), nullable=True),
        sa.Column("ref_id", sa.String(length=64), nullable=True),
        sa.Column("remark", sa.String(length=256), nullable=True),
        sa.Column(
            "created_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "ref_type IS NULL OR ref_type IN ('bill_hourly', 'bill_daily_disk', 'order', "
            "'adjustment', 'refund_request', 'subscription')",
            name=op.f("ck_balance_ledger_ref_type"),
        ),
        sa.CheckConstraint("amount <> 0", name=op.f("ck_balance_ledger_amount_nonzero")),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_balance_ledger")),
    )
    op.create_index(op.f("ix_balance_ledger_user_id"), "balance_ledger", ["user_id"], unique=False)
    op.create_table(
        "bills_daily_disk",
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.Column("disk_id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("day", sa.TIMESTAMP(timezone=True), nullable=False),
        sa.Column("size_gb", sa.Integer(), nullable=False),
        sa.Column("unit_price", sa.Numeric(precision=12, scale=4), nullable=False),
        sa.Column("amount", sa.Numeric(precision=14, scale=2), nullable=False),
        sa.Column(
            "created_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint("amount >= 0", name=op.f("ck_bills_daily_disk_amount_nonneg")),
        sa.CheckConstraint("size_gb >= 0", name=op.f("ck_bills_daily_disk_size_nonneg")),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_bills_daily_disk")),
        sa.UniqueConstraint("disk_id", "day", name=op.f("uq_bills_daily_disk_disk_id_day")),
    )
    op.create_index(
        "ix_bills_daily_disk_user_day", "bills_daily_disk", ["user_id", "day"], unique=False
    )
    op.create_index(
        op.f("ix_bills_daily_disk_user_id"), "bills_daily_disk", ["user_id"], unique=False
    )
    op.create_table(
        "bills_hourly",
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.Column("instance_id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("hour_start", sa.TIMESTAMP(timezone=True), nullable=False),
        sa.Column("seconds_used", sa.Integer(), nullable=False),
        sa.Column("unit_price", sa.Numeric(precision=12, scale=4), nullable=False),
        sa.Column("gpu_count", sa.Integer(), nullable=False),
        sa.Column("amount", sa.Numeric(precision=14, scale=2), nullable=False),
        sa.Column("detail", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column(
            "created_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint("amount >= 0", name=op.f("ck_bills_hourly_amount_nonneg")),
        sa.CheckConstraint(
            "seconds_used >= 0 AND seconds_used <= 3600", name=op.f("ck_bills_hourly_seconds_range")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_bills_hourly")),
        sa.UniqueConstraint(
            "instance_id", "hour_start", name=op.f("uq_bills_hourly_instance_id_hour_start")
        ),
    )
    op.create_index(
        op.f("ix_bills_hourly_hour_start"), "bills_hourly", ["hour_start"], unique=False
    )
    op.create_index(
        "ix_bills_hourly_user_hour", "bills_hourly", ["user_id", "hour_start"], unique=False
    )
    op.create_index(op.f("ix_bills_hourly_user_id"), "bills_hourly", ["user_id"], unique=False)
    op.create_table(
        "cluster_status",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("api_reachable", sa.Boolean(), nullable=False),
        sa.Column("k8s_version", sa.String(length=64), nullable=True),
        sa.Column("distro", sa.String(length=16), nullable=True),
        sa.Column("hami_ready", sa.Boolean(), nullable=False),
        sa.Column("dcgm_present", sa.Boolean(), nullable=False),
        sa.Column("kps_present", sa.Boolean(), nullable=False),
        sa.Column("gpu_operator_present", sa.Boolean(), nullable=False),
        sa.Column("kata_runtimeclass", sa.Boolean(), nullable=False),
        sa.Column("nvidia_runtimeclass", sa.Boolean(), server_default="false", nullable=False),
        sa.Column("gateway_ready", sa.Boolean(), server_default="false", nullable=False),
        sa.Column("cert_manager_ready", sa.Boolean(), server_default="false", nullable=False),
        sa.Column("nodes_ready", sa.Integer(), server_default="0", nullable=False),
        sa.Column("nodes_total", sa.Integer(), server_default="0", nullable=False),
        sa.Column("storage_classes", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("pools", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("error", sa.Text(), nullable=True),
        sa.Column("probed_at", sa.TIMESTAMP(timezone=True), nullable=False),
        sa.CheckConstraint("id = 1", name=op.f("ck_cluster_status_singleton")),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_cluster_status")),
    )
    op.create_table(
        "data_disks",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("uuid", sa.String(length=32), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=64), nullable=False),
        sa.Column("size_gb", sa.Integer(), nullable=False),
        sa.Column("juicefs_subpath", sa.String(length=128), nullable=False),
        sa.Column("price_gb_month", sa.Numeric(precision=12, scale=4), nullable=False),
        sa.Column("idempotency_key", sa.String(length=64), nullable=True),
        sa.Column("request_fingerprint", sa.String(length=64), nullable=True),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("mounted_instance_id", sa.Integer(), nullable=True),
        sa.Column("grace_started_at", sa.TIMESTAMP(timezone=True), nullable=True),
        sa.Column("grace_ended_at", sa.TIMESTAMP(timezone=True), nullable=True),
        sa.Column("frozen_started_at", sa.TIMESTAMP(timezone=True), nullable=True),
        sa.Column("quota_synced", sa.Boolean(), server_default="false", nullable=False),
        sa.Column(
            "created_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_data_disks")),
        sa.UniqueConstraint("juicefs_subpath", name=op.f("uq_data_disks_juicefs_subpath")),
        sa.UniqueConstraint(
            "user_id", "idempotency_key", name=op.f("uq_data_disks_user_id_idempotency_key")
        ),
        sa.UniqueConstraint("uuid", name=op.f("uq_data_disks_uuid")),
    )
    op.create_index(
        op.f("ix_data_disks_mounted_instance_id"),
        "data_disks",
        ["mounted_instance_id"],
        unique=False,
    )
    op.create_index(op.f("ix_data_disks_status"), "data_disks", ["status"], unique=False)
    op.create_index(op.f("ix_data_disks_user_id"), "data_disks", ["user_id"], unique=False)
    op.create_index(
        "uq_data_disks_mounted_instance",
        "data_disks",
        ["mounted_instance_id"],
        unique=True,
        postgresql_where=sa.text("mounted_instance_id IS NOT NULL"),
    )
    op.create_table(
        "images",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("framework", sa.String(length=32), nullable=False),
        sa.Column("framework_version", sa.String(length=32), nullable=False),
        sa.Column("python_version", sa.String(length=16), nullable=False),
        sa.Column("cuda_version", sa.String(length=16), nullable=False),
        sa.Column("image_ref", sa.String(length=256), nullable=False),
        sa.Column("prewarm_enabled", sa.Boolean(), nullable=False),
        sa.Column("sort", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_images")),
        sa.UniqueConstraint("image_ref", name=op.f("uq_images_image_ref")),
    )
    op.create_table(
        "instance_events",
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.Column("instance_id", sa.Integer(), nullable=False),
        sa.Column("from_status", sa.String(length=16), nullable=True),
        sa.Column("to_status", sa.String(length=16), nullable=False),
        sa.Column("reason", sa.String(length=64), nullable=False),
        sa.Column("actor", sa.String(length=16), nullable=False),
        sa.Column("metadata", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column(
            "created_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_instance_events")),
    )
    op.create_index(
        op.f("ix_instance_events_created_at"), "instance_events", ["created_at"], unique=False
    )
    op.create_index(
        op.f("ix_instance_events_instance_id"), "instance_events", ["instance_id"], unique=False
    )
    op.create_table(
        "instances",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("uuid", sa.String(length=32), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=64), nullable=False),
        sa.Column("sku_id", sa.Integer(), nullable=False),
        sa.Column("spec", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("price_hourly", sa.Numeric(precision=12, scale=4), nullable=False),
        sa.Column("gpu_count", sa.Integer(), nullable=False),
        sa.Column("image_ref", sa.String(length=256), nullable=False),
        sa.Column("market", sa.String(length=16), server_default="on_demand", nullable=False),
        sa.Column("workload_type", sa.String(length=8), server_default="dev", nullable=False),
        sa.Column("container_command", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("container_args", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("with_ssh", sa.Boolean(), server_default="true", nullable=False),
        sa.Column("env_encrypted", sa.Text(), nullable=True),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("k8s_namespace", sa.String(length=64), nullable=False),
        sa.Column("node_name", sa.String(length=253), nullable=True),
        sa.Column("ssh_port", sa.Integer(), nullable=True),
        sa.Column("jupyter_token", sa.String(length=160), nullable=False),
        sa.Column("authorized_keys", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("data_disk_id", sa.Integer(), nullable=True),
        sa.Column("idempotency_key", sa.String(length=64), nullable=True),
        sa.Column("request_fingerprint", sa.String(length=64), nullable=True),
        sa.Column("frozen_deadline", sa.TIMESTAMP(timezone=True), nullable=True),
        sa.Column("unready_since", sa.TIMESTAMP(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "market IN ('on_demand', 'spot', 'subscription')", name=op.f("ck_instances_market")
        ),
        sa.CheckConstraint(
            "status IN ('creating', 'running', 'stopping', 'stopped', 'starting', 'frozen', "
            "'releasing', 'released', 'failed')",
            name=op.f("ck_instances_status"),
        ),
        sa.CheckConstraint(
            "workload_type IN ('dev', 'service')", name=op.f("ck_instances_workload_type")
        ),
        sa.CheckConstraint("gpu_count >= 0", name=op.f("ck_instances_gpu_count_nonneg")),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_instances")),
        sa.UniqueConstraint(
            "user_id", "idempotency_key", name=op.f("uq_instances_user_id_idempotency_key")
        ),
        sa.UniqueConstraint("uuid", name=op.f("uq_instances_uuid")),
    )
    op.create_index(op.f("ix_instances_status"), "instances", ["status"], unique=False)
    op.create_index(op.f("ix_instances_user_id"), "instances", ["user_id"], unique=False)
    op.create_table(
        "invoice_requests",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("period", sa.String(length=7), nullable=False),
        sa.Column("title_type", sa.String(length=16), nullable=False),
        sa.Column("title", sa.String(length=128), nullable=False),
        sa.Column("tax_id", sa.String(length=32), nullable=True),
        sa.Column("email", sa.String(length=128), nullable=False),
        sa.Column("amount", sa.Numeric(precision=12, scale=2), nullable=False),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("invoice_no", sa.String(length=64), nullable=True),
        sa.Column("reject_reason", sa.String(length=256), nullable=True),
        sa.Column("issued_by", sa.Integer(), nullable=True),
        sa.Column("issued_at", sa.TIMESTAMP(timezone=True), nullable=True),
        sa.Column("idempotency_key", sa.String(length=64), nullable=True),
        sa.Column("request_fingerprint", sa.String(length=64), nullable=True),
        sa.Column(
            "created_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "status IN ('submitted', 'issued', 'rejected')", name=op.f("ck_invoice_requests_status")
        ),
        sa.CheckConstraint(
            "title_type IN ('personal', 'company')", name=op.f("ck_invoice_requests_title_type")
        ),
        sa.CheckConstraint("amount > 0", name=op.f("ck_invoice_requests_amount_positive")),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_invoice_requests")),
        sa.UniqueConstraint(
            "user_id", "idempotency_key", name=op.f("uq_invoice_requests_user_id_idempotency_key")
        ),
    )
    op.create_index(
        op.f("ix_invoice_requests_status"), "invoice_requests", ["status"], unique=False
    )
    op.create_index(
        op.f("ix_invoice_requests_user_id"), "invoice_requests", ["user_id"], unique=False
    )
    op.create_index(
        "uq_invoice_requests_active_period",
        "invoice_requests",
        ["user_id", "period"],
        unique=True,
        postgresql_where=sa.text("status IN ('submitted', 'issued')"),
    )
    op.create_table(
        "legal_doc_versions",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("doc_key", sa.String(length=32), nullable=False),
        sa.Column("locale", sa.String(length=16), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("title", sa.String(length=128), nullable=False),
        sa.Column("content_md", sa.Text(), nullable=False),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("effective_note", sa.String(length=512), nullable=True),
        sa.Column("created_by", sa.Integer(), nullable=True),
        sa.Column(
            "created_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("published_by", sa.Integer(), nullable=True),
        sa.Column("published_at", sa.TIMESTAMP(timezone=True), nullable=True),
        sa.CheckConstraint(
            "status IN ('draft', 'published', 'archived')",
            name=op.f("ck_legal_doc_versions_status"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_legal_doc_versions")),
        sa.UniqueConstraint(
            "doc_key",
            "locale",
            "version",
            name=op.f("uq_legal_doc_versions_doc_key_locale_version"),
        ),
    )
    op.create_index(
        op.f("ix_legal_doc_versions_status"), "legal_doc_versions", ["status"], unique=False
    )
    op.create_index(
        "uq_legal_doc_versions_one_published",
        "legal_doc_versions",
        ["doc_key", "locale"],
        unique=True,
        postgresql_where=sa.text("status = 'published'"),
    )
    op.create_table(
        "node_enrollments",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("token_hash", sa.String(length=64), nullable=False),
        sa.Column("progress_token_hash", sa.String(length=64), nullable=True),
        sa.Column("pool", sa.String(length=8), nullable=False),
        sa.Column("hostname", sa.String(length=253), nullable=True),
        sa.Column("note", sa.String(length=128), nullable=True),
        sa.Column("nvme_devices", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("phase", sa.String(length=32), nullable=True),
        sa.Column("error", sa.Text(), nullable=True),
        sa.Column("node_name", sa.String(length=253), nullable=True),
        sa.Column("reported_ip", sa.String(length=64), nullable=True),
        sa.Column("os_info", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("gpu_info", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("expires_at", sa.TIMESTAMP(timezone=True), nullable=False),
        sa.Column("last_report_at", sa.TIMESTAMP(timezone=True), nullable=True),
        sa.Column("joined_at", sa.TIMESTAMP(timezone=True), nullable=True),
        sa.Column("created_by", sa.Integer(), nullable=False),
        sa.Column("idempotency_key", sa.String(length=64), nullable=True),
        sa.Column(
            "created_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_node_enrollments")),
        sa.UniqueConstraint(
            "created_by",
            "idempotency_key",
            name=op.f("uq_node_enrollments_created_by_idempotency_key"),
        ),
        sa.UniqueConstraint(
            "progress_token_hash", name=op.f("uq_node_enrollments_progress_token_hash")
        ),
        sa.UniqueConstraint("token_hash", name=op.f("uq_node_enrollments_token_hash")),
    )
    op.create_index(
        op.f("ix_node_enrollments_status"), "node_enrollments", ["status"], unique=False
    )
    op.create_table(
        "node_specs",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("node_name", sa.String(length=253), nullable=False),
        sa.Column("pool_label", sa.String(length=32), nullable=True),
        sa.Column("unlabeled", sa.Boolean(), nullable=False),
        sa.Column("gpu_model_raw", sa.String(length=128), nullable=True),
        sa.Column("gpu_model", sa.String(length=32), nullable=True),
        sa.Column("label_synced", sa.Boolean(), nullable=False),
        sa.Column("gpu_count", sa.Integer(), nullable=False),
        sa.Column("gpu_used", sa.Integer(), nullable=False),
        sa.Column("vram_gb", sa.Integer(), nullable=False),
        sa.Column("vcpu", sa.Integer(), nullable=False),
        sa.Column("mem_gb", sa.Integer(), nullable=False),
        sa.Column("disk_gb", sa.Integer(), nullable=False),
        sa.Column("driver_version", sa.String(length=32), nullable=True),
        sa.Column("cuda_version", sa.String(length=16), nullable=True),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("desired_unschedulable", sa.Boolean(), nullable=True),
        sa.Column("last_seen", sa.TIMESTAMP(timezone=True), nullable=False),
        sa.Column(
            "created_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_node_specs")),
        sa.UniqueConstraint("node_name", name=op.f("uq_node_specs_node_name")),
    )
    op.create_index(op.f("ix_node_specs_status"), "node_specs", ["status"], unique=False)
    op.create_table(
        "notifications",
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=True),
        sa.Column("type", sa.String(length=32), nullable=False),
        sa.Column("title", sa.String(length=128), nullable=False),
        sa.Column("content", sa.Text(), nullable=False),
        sa.Column("target_id", sa.String(length=64), nullable=True),
        sa.Column("severity", sa.String(length=16), nullable=False),
        sa.Column("status", sa.String(length=16), server_default="published", nullable=False),
        sa.Column("dedup_key", sa.String(length=128), nullable=True),
        sa.Column("read_at", sa.TIMESTAMP(timezone=True), nullable=True),
        sa.Column("acked_by", sa.Integer(), nullable=True),
        sa.Column("acked_at", sa.TIMESTAMP(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_notifications")),
        sa.UniqueConstraint("dedup_key", name=op.f("uq_notifications_dedup_key")),
    )
    op.create_index(op.f("ix_notifications_type"), "notifications", ["type"], unique=False)
    op.create_index(op.f("ix_notifications_user_id"), "notifications", ["user_id"], unique=False)
    op.create_table(
        "orders",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("order_no", sa.String(length=40), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("amount", sa.Numeric(precision=14, scale=2), nullable=False),
        sa.Column("channel", sa.String(length=16), nullable=False),
        sa.Column("channel_txn_id", sa.String(length=64), nullable=True),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("idempotency_key", sa.String(length=64), nullable=True),
        sa.Column("request_fingerprint", sa.String(length=64), nullable=True),
        sa.Column("backfill_idempotency_key", sa.String(length=64), nullable=True),
        sa.Column("qr_url", sa.String(length=512), nullable=True),
        sa.Column("paid_at", sa.TIMESTAMP(timezone=True), nullable=True),
        sa.Column("channel_reversed_at", sa.TIMESTAMP(timezone=True), nullable=True),
        sa.Column("expires_at", sa.TIMESTAMP(timezone=True), nullable=False),
        sa.Column(
            "created_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "status IN ('pending', 'paid', 'failed', 'closed')", name=op.f("ck_orders_status")
        ),
        sa.CheckConstraint("amount > 0", name=op.f("ck_orders_amount_positive")),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_orders")),
        sa.UniqueConstraint(
            "backfill_idempotency_key", name=op.f("uq_orders_backfill_idempotency_key")
        ),
        sa.UniqueConstraint("channel_txn_id", name=op.f("uq_orders_channel_txn_id")),
        sa.UniqueConstraint("order_no", name=op.f("uq_orders_order_no")),
        sa.UniqueConstraint(
            "user_id", "idempotency_key", name=op.f("uq_orders_user_id_idempotency_key")
        ),
    )
    op.create_index(op.f("ix_orders_status"), "orders", ["status"], unique=False)
    op.create_index(op.f("ix_orders_user_id"), "orders", ["user_id"], unique=False)
    op.create_table(
        "outbox_tasks",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("type", sa.String(length=64), nullable=False),
        sa.Column("payload", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("retries", sa.Integer(), nullable=False),
        sa.Column(
            "next_retry_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("locked_by", sa.String(length=128), nullable=True),
        sa.Column("locked_at", sa.TIMESTAMP(timezone=True), nullable=True),
        sa.Column("last_error", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "status IN ('pending', 'running', 'done', 'dead', 'discarded')",
            name=op.f("ck_outbox_tasks_status"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_outbox_tasks")),
    )
    op.create_index(
        op.f("ix_outbox_tasks_next_retry_at"), "outbox_tasks", ["next_retry_at"], unique=False
    )
    op.create_index(op.f("ix_outbox_tasks_status"), "outbox_tasks", ["status"], unique=False)
    op.create_index(
        "ix_outbox_tasks_status_next_retry_at_id",
        "outbox_tasks",
        ["status", "next_retry_at", "id"],
        unique=False,
    )
    op.create_index(op.f("ix_outbox_tasks_type"), "outbox_tasks", ["type"], unique=False)
    op.create_table(
        "platform_settings",
        sa.Column("key", sa.String(length=64), nullable=False),
        sa.Column("value", sa.Text(), nullable=False),
        sa.Column("updated_by", sa.Integer(), nullable=True),
        sa.Column(
            "updated_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("key", name=op.f("pk_platform_settings")),
    )
    op.create_table(
        "policy_overrides",
        sa.Column("key", sa.String(length=64), nullable=False),
        sa.Column("value", sa.String(length=64), nullable=False),
        sa.Column(
            "updated_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("key", name=op.f("pk_policy_overrides")),
    )
    op.create_table(
        "port_allocations",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("port", sa.Integer(), nullable=False),
        sa.Column("instance_id", sa.Integer(), nullable=True),
        sa.Column("blocked", sa.Boolean(), server_default="false", nullable=False),
        sa.Column(
            "updated_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_port_allocations")),
        sa.UniqueConstraint("port", name=op.f("uq_port_allocations_port")),
    )
    op.create_index(
        op.f("ix_port_allocations_instance_id"), "port_allocations", ["instance_id"], unique=False
    )
    op.create_index(
        "uq_port_allocations_instance",
        "port_allocations",
        ["instance_id"],
        unique=True,
        postgresql_where=sa.text("instance_id IS NOT NULL"),
    )
    op.create_table(
        "rate_limit_counters",
        sa.Column("key", sa.String(length=128), nullable=False),
        sa.Column("window_start", sa.TIMESTAMP(timezone=True), nullable=False),
        sa.Column("hits", sa.Integer(), nullable=False),
        sa.Column(
            "updated_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("key", name=op.f("pk_rate_limit_counters")),
    )
    op.create_table(
        "reconcile_checkpoints",
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("last_ledger_id", sa.BigInteger(), nullable=False),
        sa.Column("balance_after", sa.Numeric(precision=14, scale=2), nullable=False),
        sa.Column("updated_at", sa.TIMESTAMP(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("user_id", name=op.f("pk_reconcile_checkpoints")),
    )
    op.create_table(
        "refund_requests",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("refund_no", sa.String(length=20), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("order_no", sa.String(length=40), nullable=False),
        sa.Column("amount", sa.Numeric(precision=12, scale=2), nullable=False),
        sa.Column("reason", sa.String(length=256), nullable=False),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("review_by", sa.Integer(), nullable=True),
        sa.Column("review_at", sa.TIMESTAMP(timezone=True), nullable=True),
        sa.Column("review_comment", sa.String(length=256), nullable=True),
        sa.Column("payout_channel", sa.String(length=32), nullable=True),
        sa.Column("payout_ref", sa.String(length=128), nullable=True),
        sa.Column("payout_by", sa.Integer(), nullable=True),
        sa.Column("payout_at", sa.TIMESTAMP(timezone=True), nullable=True),
        sa.Column("wallet_entry_id", sa.BigInteger(), nullable=True),
        sa.Column("idempotency_key", sa.String(length=64), nullable=True),
        sa.Column("request_fingerprint", sa.String(length=64), nullable=True),
        sa.Column("payout_idempotency_key", sa.String(length=64), nullable=True),
        sa.Column("payout_request_fingerprint", sa.String(length=64), nullable=True),
        sa.Column(
            "created_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "status IN ('pending', 'approved', 'rejected', 'paid', 'cancelled')",
            name=op.f("ck_refund_requests_status"),
        ),
        sa.CheckConstraint("amount > 0", name=op.f("ck_refund_requests_amount_positive")),
        sa.CheckConstraint(
            "payout_by IS NULL OR review_by IS NULL OR payout_by <> review_by",
            name=op.f("ck_refund_requests_payout_not_reviewer"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_refund_requests")),
        sa.UniqueConstraint("refund_no", name=op.f("uq_refund_requests_refund_no")),
        sa.UniqueConstraint(
            "user_id", "idempotency_key", name=op.f("uq_refund_requests_user_id_idempotency_key")
        ),
    )
    op.create_index(op.f("ix_refund_requests_status"), "refund_requests", ["status"], unique=False)
    op.create_index(
        op.f("ix_refund_requests_user_id"), "refund_requests", ["user_id"], unique=False
    )
    op.create_index(
        "uq_refund_requests_active_order",
        "refund_requests",
        ["order_no"],
        unique=True,
        postgresql_where=sa.text("status IN ('pending', 'approved')"),
    )
    op.create_table(
        "service_api_keys",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("instance_id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=64), nullable=False),
        sa.Column("key_hash", sa.String(length=64), nullable=False),
        sa.Column("key_prefix", sa.String(length=16), nullable=False),
        sa.Column("last_used_at", sa.TIMESTAMP(timezone=True), nullable=True),
        sa.Column("revoked_at", sa.TIMESTAMP(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_service_api_keys")),
        sa.UniqueConstraint("key_hash", name=op.f("uq_service_api_keys_key_hash")),
    )
    op.create_index(
        op.f("ix_service_api_keys_instance_id"), "service_api_keys", ["instance_id"], unique=False
    )
    op.create_index(
        op.f("ix_service_api_keys_user_id"), "service_api_keys", ["user_id"], unique=False
    )
    op.create_table(
        "service_endpoints",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("instance_id", sa.Integer(), nullable=False),
        sa.Column("public_slug", sa.String(length=32), nullable=False),
        sa.Column("container_port", sa.Integer(), nullable=False),
        sa.Column("health_path", sa.String(length=128), nullable=True),
        sa.Column("require_api_key", sa.Boolean(), server_default="true", nullable=False),
        sa.Column(
            "created_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "container_port BETWEEN 1 AND 65535 AND container_port NOT IN (22, 8888)",
            name=op.f("ck_service_endpoints_container_port"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_service_endpoints")),
        sa.UniqueConstraint("instance_id", name=op.f("uq_service_endpoints_instance_id")),
        sa.UniqueConstraint("public_slug", name=op.f("uq_service_endpoints_public_slug")),
    )
    op.create_table(
        "settlement_gaps",
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.Column("kind", sa.String(length=16), nullable=False),
        sa.Column("window_start", sa.TIMESTAMP(timezone=True), nullable=False),
        sa.Column("object_id", sa.BigInteger(), nullable=False),
        sa.Column("reason", sa.String(length=32), nullable=False),
        sa.Column("resolved_at", sa.TIMESTAMP(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_settlement_gaps")),
        sa.UniqueConstraint(
            "kind",
            "window_start",
            "object_id",
            name=op.f("uq_settlement_gaps_kind_window_start_object_id"),
        ),
    )
    op.create_table(
        "settlement_watermarks",
        sa.Column("key", sa.String(length=16), nullable=False),
        sa.Column("settled_through", sa.TIMESTAMP(timezone=True), nullable=False),
        sa.Column(
            "updated_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("key", name=op.f("pk_settlement_watermarks")),
    )
    op.create_table(
        "skus",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=64), nullable=False),
        sa.Column("gpu_model", sa.String(length=32), nullable=False),
        sa.Column("tier", sa.String(length=16), nullable=False),
        sa.Column("mig_profile", sa.String(length=32), nullable=True),
        sa.Column("gpu_cores_pct", sa.Integer(), nullable=False),
        sa.Column("vram_gb", sa.Integer(), nullable=False),
        sa.Column("oversell_cores", sa.Numeric(precision=4, scale=2), nullable=False),
        sa.Column("pool_label", sa.String(length=32), nullable=False),
        sa.Column("vcpu", sa.Integer(), nullable=False),
        sa.Column("mem_gb", sa.Integer(), nullable=False),
        sa.Column("disk_gb", sa.Integer(), nullable=False),
        sa.Column("price_hourly", sa.Numeric(precision=12, scale=4), nullable=False),
        sa.Column("max_gpus_per_instance", sa.Integer(), nullable=False),
        sa.Column("cuda_max", sa.String(length=16), nullable=True),
        sa.Column("period_enabled", sa.Boolean(), server_default="true", nullable=False),
        sa.Column("spot_enabled", sa.Boolean(), server_default="false", nullable=False),
        sa.Column("status", sa.String(length=8), nullable=False),
        sa.Column(
            "created_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_skus")),
    )
    op.create_index(op.f("ix_skus_gpu_model"), "skus", ["gpu_model"], unique=False)
    op.create_index(op.f("ix_skus_status"), "skus", ["status"], unique=False)
    op.create_index(op.f("ix_skus_tier"), "skus", ["tier"], unique=False)
    op.create_index(
        "uq_skus_business_key",
        "skus",
        ["gpu_model", "tier", "pool_label", "mig_profile", "gpu_cores_pct", "vcpu", "mem_gb"],
        unique=True,
        postgresql_nulls_not_distinct=True,
    )
    op.create_table(
        "sms_codes",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("phone", sa.String(length=20), nullable=False),
        sa.Column("code_hash", sa.String(length=64), nullable=False),
        sa.Column("purpose", sa.String(length=16), nullable=False),
        sa.Column("expires_at", sa.TIMESTAMP(timezone=True), nullable=False),
        sa.Column("used_at", sa.TIMESTAMP(timezone=True), nullable=True),
        sa.Column("attempts", sa.Integer(), nullable=False),
        sa.Column(
            "created_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_sms_codes")),
    )
    op.create_index(op.f("ix_sms_codes_phone"), "sms_codes", ["phone"], unique=False)
    op.create_table(
        "ssh_keys",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=64), nullable=False),
        sa.Column("public_key", sa.Text(), nullable=False),
        sa.Column("fingerprint", sa.String(length=64), nullable=False),
        sa.Column(
            "created_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_ssh_keys")),
        sa.UniqueConstraint("user_id", "fingerprint", name=op.f("uq_ssh_keys_user_id_fingerprint")),
    )
    op.create_index(op.f("ix_ssh_keys_user_id"), "ssh_keys", ["user_id"], unique=False)
    op.create_table(
        "subscriptions",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("instance_id", sa.Integer(), nullable=False),
        sa.Column("sku_id", sa.Integer(), nullable=False),
        sa.Column("period", sa.String(length=8), nullable=False),
        sa.Column("period_count", sa.Integer(), nullable=False),
        sa.Column("unit_price", sa.Numeric(precision=12, scale=4), nullable=False),
        sa.Column("amount_paid", sa.Numeric(precision=14, scale=2), nullable=False),
        sa.Column("started_at", sa.TIMESTAMP(timezone=True), nullable=False),
        sa.Column("expires_at", sa.TIMESTAMP(timezone=True), nullable=False),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("auto_renew", sa.Boolean(), server_default="false", nullable=False),
        sa.Column("renewed_from_id", sa.Integer(), nullable=True),
        sa.Column("warned_for_expiry", sa.TIMESTAMP(timezone=True), nullable=True),
        sa.Column("idempotency_key", sa.String(length=64), nullable=True),
        sa.Column("request_fingerprint", sa.String(length=64), nullable=True),
        sa.Column(
            "created_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "period IN ('day', 'week', 'month', 'year')", name=op.f("ck_subscriptions_period")
        ),
        sa.CheckConstraint(
            "status IN ('active', 'expired', 'cancelled')", name=op.f("ck_subscriptions_status")
        ),
        sa.CheckConstraint("amount_paid >= 0", name=op.f("ck_subscriptions_amount_nonneg")),
        sa.CheckConstraint(
            "period_count >= 1", name=op.f("ck_subscriptions_period_count_positive")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_subscriptions")),
        sa.UniqueConstraint(
            "user_id", "idempotency_key", name=op.f("uq_subscriptions_user_id_idempotency_key")
        ),
    )
    op.create_index(
        "ix_subscriptions_active_expiry",
        "subscriptions",
        ["expires_at"],
        unique=False,
        postgresql_where=sa.text("status = 'active'"),
    )
    op.create_index(
        op.f("ix_subscriptions_expires_at"), "subscriptions", ["expires_at"], unique=False
    )
    op.create_index(
        op.f("ix_subscriptions_instance_id"), "subscriptions", ["instance_id"], unique=False
    )
    op.create_index(op.f("ix_subscriptions_status"), "subscriptions", ["status"], unique=False)
    op.create_index(op.f("ix_subscriptions_user_id"), "subscriptions", ["user_id"], unique=False)
    op.create_index(
        "uq_subscriptions_active_instance",
        "subscriptions",
        ["instance_id"],
        unique=True,
        postgresql_where=sa.text("status = 'active'"),
    )
    op.create_table(
        "tickets",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("ticket_no", sa.String(length=20), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("category", sa.String(length=16), nullable=False),
        sa.Column("subject", sa.String(length=128), nullable=False),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("instance_uuid", sa.String(length=32), nullable=True),
        sa.Column("idempotency_key", sa.String(length=64), nullable=True),
        sa.Column(
            "created_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("closed_at", sa.TIMESTAMP(timezone=True), nullable=True),
        sa.CheckConstraint(
            "category IN ('instance', 'billing', 'data', 'account', 'other')",
            name=op.f("ck_tickets_category"),
        ),
        sa.CheckConstraint(
            "status IN ('open', 'pending_staff', 'pending_user', 'resolved', 'closed')",
            name=op.f("ck_tickets_status"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_tickets")),
        sa.UniqueConstraint("ticket_no", name=op.f("uq_tickets_ticket_no")),
        sa.UniqueConstraint(
            "user_id", "idempotency_key", name=op.f("uq_tickets_user_id_idempotency_key")
        ),
    )
    op.create_index(op.f("ix_tickets_status"), "tickets", ["status"], unique=False)
    op.create_index(op.f("ix_tickets_user_id"), "tickets", ["user_id"], unique=False)
    op.create_table(
        "usage_hourly",
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.Column("instance_id", sa.Integer(), nullable=False),
        sa.Column("hour_start", sa.TIMESTAMP(timezone=True), nullable=False),
        sa.Column("gpu_util_avg", sa.Float(), nullable=True),
        sa.Column(
            "created_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_usage_hourly")),
        sa.UniqueConstraint(
            "instance_id", "hour_start", name=op.f("uq_usage_hourly_instance_id_hour_start")
        ),
    )
    op.create_index(
        op.f("ix_usage_hourly_hour_start"), "usage_hourly", ["hour_start"], unique=False
    )
    op.create_index(
        op.f("ix_usage_hourly_instance_id"), "usage_hourly", ["instance_id"], unique=False
    )
    op.create_table(
        "used_refresh_tokens",
        sa.Column("jti", sa.String(length=32), nullable=False),
        sa.Column("expires_at", sa.TIMESTAMP(timezone=True), nullable=False),
        sa.Column(
            "used_at", sa.TIMESTAMP(timezone=True), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column("consumed_via", sa.String(length=16), nullable=True),
        sa.Column("replaced_refresh_jti", sa.String(length=32), nullable=True),
        sa.Column("replaced_access_jti", sa.String(length=32), nullable=True),
        sa.Column("replaced_iat", sa.TIMESTAMP(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("jti", name=op.f("pk_used_refresh_tokens")),
    )
    op.create_index(
        op.f("ix_used_refresh_tokens_expires_at"),
        "used_refresh_tokens",
        ["expires_at"],
        unique=False,
    )
    op.create_table(
        "user_consents",
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("doc_key", sa.String(length=32), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column(
            "accepted_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("client_ip", sa.String(length=45), nullable=True),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_user_consents")),
    )
    op.create_index(op.f("ix_user_consents_user_id"), "user_consents", ["user_id"], unique=False)
    op.create_table(
        "user_quota_overrides",
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("max_gpus", sa.Integer(), nullable=True),
        sa.Column("max_instances", sa.Integer(), nullable=True),
        sa.Column("max_disks", sa.Integer(), nullable=True),
        sa.Column("note", sa.String(length=200), nullable=False),
        sa.Column("updated_by", sa.Integer(), nullable=False),
        sa.Column(
            "updated_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("user_id", name=op.f("pk_user_quota_overrides")),
    )
    op.create_table(
        "users",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("phone", sa.String(length=40), nullable=False),
        sa.Column("password_hash", sa.String(length=128), nullable=True),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("low_balance_warn_hours", sa.Integer(), nullable=False),
        sa.Column("token_version", sa.Integer(), nullable=False),
        sa.Column("verification_status", sa.String(length=16), nullable=False),
        sa.Column("id_name", sa.String(length=64), nullable=True),
        sa.Column("id_number", sa.String(length=32), nullable=True),
        sa.Column(
            "created_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_users")),
        sa.UniqueConstraint("phone", name=op.f("uq_users_phone")),
    )
    op.create_index(
        "ix_users_status_not_active",
        "users",
        ["status"],
        unique=False,
        postgresql_where=sa.text("status <> 'active'"),
    )
    op.create_table(
        "wallets",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("balance", sa.Numeric(precision=14, scale=2), nullable=False),
        sa.Column("frozen", sa.Numeric(precision=14, scale=2), nullable=False),
        sa.Column(
            "updated_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint("frozen >= 0", name=op.f("ck_wallets_frozen_nonneg")),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_wallets")),
        sa.UniqueConstraint("user_id", name=op.f("uq_wallets_user_id")),
    )
    op.create_table(
        "image_node_cache",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("image_id", sa.Integer(), nullable=False),
        sa.Column("node_name", sa.String(length=255), nullable=False),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("cached_ref", sa.String(length=256), nullable=True),
        sa.Column("last_error", sa.Text(), nullable=True),
        sa.Column("checked_at", sa.TIMESTAMP(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["image_id"],
            ["images.id"],
            name=op.f("fk_image_node_cache_image_id_images"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_image_node_cache")),
        sa.UniqueConstraint(
            "image_id", "node_name", name=op.f("uq_image_node_cache_image_id_node_name")
        ),
    )
    op.create_index(
        op.f("ix_image_node_cache_image_id"), "image_node_cache", ["image_id"], unique=False
    )
    op.create_index(
        op.f("ix_image_node_cache_status"), "image_node_cache", ["status"], unique=False
    )
    op.create_table(
        "ticket_messages",
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.Column("ticket_id", sa.Integer(), nullable=False),
        sa.Column("sender_kind", sa.String(length=8), nullable=False),
        sa.Column("sender_id", sa.Integer(), nullable=False),
        sa.Column("body", sa.String(length=4000), nullable=False),
        sa.Column(
            "created_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "sender_kind IN ('user', 'staff')", name=op.f("ck_ticket_messages_sender_kind")
        ),
        sa.ForeignKeyConstraint(
            ["ticket_id"], ["tickets.id"], name=op.f("fk_ticket_messages_ticket_id_tickets")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_ticket_messages")),
    )
    op.create_index(
        op.f("ix_ticket_messages_ticket_id"), "ticket_messages", ["ticket_id"], unique=False
    )
    # ### end Alembic commands ###

    # —— 以下为手工维护的预置数据与存储参数(autogenerate 不产出)——

    # 法务文档预置:zh-CN published v1(发布人留空 = 系统预置;
    # legal/service.py 依赖「生产必有 published 行」,seed 脚本不种)
    versions = sa.table(
        "legal_doc_versions",
        sa.column("doc_key", sa.String),
        sa.column("locale", sa.String),
        sa.column("version", sa.Integer),
        sa.column("title", sa.String),
        sa.column("content_md", sa.Text),
        sa.column("status", sa.String),
        sa.column("effective_note", sa.String),
        sa.column("published_at", sa.TIMESTAMP(timezone=True)),
    )
    op.bulk_insert(
        versions,
        [
            {
                "doc_key": doc_key,
                "locale": "zh-CN",
                "version": 1,
                "title": title,
                "content_md": content_md,
                "status": "published",
                "effective_note": "系统预置",
                "published_at": datetime.now(UTC),
            }
            for doc_key, title, content_md in [
                ("terms", TERMS_TITLE, TERMS_MD),
                ("privacy", PRIVACY_TITLE, PRIVACY_MD),
                ("deletion_notice", DELETION_NOTICE_TITLE, DELETION_NOTICE_MD),
            ]
        ],
    )

    # 端口池已知占用先入库(与 Settings.ssh_port_excluded 同源;运行期跳过 + 数据兜底)
    op.execute(
        "INSERT INTO port_allocations (port, instance_id, blocked) VALUES (30500, NULL, true) "
        "ON CONFLICT (port) DO UPDATE SET blocked = true"
    )

    # HOT 更新友好的填充因子(存储参数不入 SQLAlchemy metadata)
    op.execute("ALTER TABLE rate_limit_counters SET (fillfactor=80)")
    op.execute("ALTER TABLE outbox_tasks SET (fillfactor=85)")


def downgrade() -> None:
    raise NotImplementedError(
        "不支持回滚:停机发布模型(stop → alembic upgrade head → start),无 downgrade 路径"
    )
