"""settlement watermark

Revision ID: 9a5668144312
Revises: 8a79f532da54
Create Date: 2026-08-21 17:52:53.620520

"""

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = "9a5668144312"
down_revision: str | None = "8a79f532da54"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "settlement_watermarks",
        sa.Column("key", sa.String(length=16), nullable=False),
        sa.Column("settled_through", sa.TIMESTAMP(timezone=True), nullable=False),
        sa.Column(
            "updated_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("key", name=op.f("pk_settlement_watermarks")),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("settlement_watermarks")
    # ### end Alembic commands ###
