"""wp6 usage_hourly

Revision ID: 475856bc70b3
Revises: ae39947f0f23
Create Date: 2026-08-19 13:20:09.149725

"""

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = "475856bc70b3"
down_revision: str | None = "ae39947f0f23"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "usage_hourly",
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.Column("instance_id", sa.Integer(), nullable=False),
        sa.Column("hour_start", sa.TIMESTAMP(timezone=True), nullable=False),
        sa.Column("gpu_util_avg", sa.Float(), nullable=True),
        sa.Column("gpu_util_p95", sa.Float(), nullable=True),
        sa.Column("vram_max_mb", sa.Integer(), nullable=True),
        sa.Column("cpu_avg_pct", sa.Float(), nullable=True),
        sa.Column(
            "created_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_usage_hourly")),
        sa.UniqueConstraint(
            "instance_id", "hour_start", name=op.f("uq_usage_hourly_instance_id_hour_start")
        ),
    )
    op.create_index(
        op.f("ix_usage_hourly_hour_start"), "usage_hourly", ["hour_start"], unique=False
    )
    op.create_index(
        op.f("ix_usage_hourly_instance_id"), "usage_hourly", ["instance_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_usage_hourly_instance_id"), table_name="usage_hourly")
    op.drop_index(op.f("ix_usage_hourly_hour_start"), table_name="usage_hourly")
    op.drop_table("usage_hourly")
    # ### end Alembic commands ###
