"""wp26 node_specs

Revision ID: 6cef72d46b82
Revises: c8e1f3a5b7d2
Create Date: 2026-08-21 11:46:27.455043

"""

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = "6cef72d46b82"
down_revision: str | None = "c8e1f3a5b7d2"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "node_specs",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("node_name", sa.String(length=253), nullable=False),
        sa.Column("pool_label", sa.String(length=32), nullable=True),
        sa.Column("unlabeled", sa.Boolean(), nullable=False),
        sa.Column("gpu_model_raw", sa.String(length=128), nullable=True),
        sa.Column("gpu_model", sa.String(length=32), nullable=True),
        sa.Column("label_synced", sa.Boolean(), nullable=False),
        sa.Column("gpu_count", sa.Integer(), nullable=False),
        sa.Column("gpu_used", sa.Integer(), nullable=False),
        sa.Column("vram_gb", sa.Integer(), nullable=False),
        sa.Column("vcpu", sa.Integer(), nullable=False),
        sa.Column("mem_gb", sa.Integer(), nullable=False),
        sa.Column("disk_gb", sa.Integer(), nullable=False),
        sa.Column("driver_version", sa.String(length=32), nullable=True),
        sa.Column("cuda_version", sa.String(length=16), nullable=True),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("last_seen", sa.TIMESTAMP(timezone=True), nullable=False),
        sa.Column(
            "created_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_node_specs")),
        sa.UniqueConstraint("node_name", name=op.f("uq_node_specs_node_name")),
    )
    op.create_index(op.f("ix_node_specs_gpu_model"), "node_specs", ["gpu_model"], unique=False)
    op.create_index(op.f("ix_node_specs_pool_label"), "node_specs", ["pool_label"], unique=False)
    op.create_index(op.f("ix_node_specs_status"), "node_specs", ["status"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_node_specs_status"), table_name="node_specs")
    op.drop_index(op.f("ix_node_specs_pool_label"), table_name="node_specs")
    op.drop_index(op.f("ix_node_specs_gpu_model"), table_name="node_specs")
    op.drop_table("node_specs")
    # ### end Alembic commands ###
