"""rate limit counters

Revision ID: 9f48acb0ecbe
Revises: 9a5668144312
Create Date: 2026-08-21 18:06:31.291476

"""

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = "9f48acb0ecbe"
down_revision: str | None = "9a5668144312"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "rate_limit_counters",
        sa.Column("key", sa.String(length=128), nullable=False),
        sa.Column("window_start", sa.TIMESTAMP(timezone=True), nullable=False),
        sa.Column("hits", sa.Integer(), nullable=False),
        sa.Column(
            "updated_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("key", name=op.f("pk_rate_limit_counters")),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("rate_limit_counters")
    # ### end Alembic commands ###
