local   all all                 trust
hostssl all all 127.0.0.1/32    scram-sha-256
hostssl all all 10.42.0.0/16    scram-sha-256
hostssl all all 172.31.36.0/24  scram-sha-256
hostnossl all all 0.0.0.0/0     reject
