SELECT format('CREATE ROLE superdl_app LOGIN NOSUPERUSER NOCREATEDB NOCREATEROLE NOINHERIT PASSWORD %L', :app_password)
WHERE NOT EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'superdl_app') \gexec
SELECT format('ALTER ROLE superdl_app WITH LOGIN NOSUPERUSER NOCREATEDB NOCREATEROLE NOINHERIT PASSWORD %L', :app_password)
WHERE EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'superdl_app') \gexec

GRANT CONNECT ON DATABASE superdl TO superdl_app;
GRANT USAGE ON SCHEMA public TO superdl_app;
GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA public TO superdl_app;
GRANT USAGE, SELECT, UPDATE ON ALL SEQUENCES IN SCHEMA public TO superdl_app;
REVOKE UPDATE, DELETE ON balance_ledger FROM superdl_app;
REVOKE UPDATE, DELETE ON audit_log FROM superdl_app;
REVOKE UPDATE, DELETE ON instance_events FROM superdl_app;
REVOKE INSERT, UPDATE, DELETE ON alembic_version FROM superdl_app;
REVOKE ALL ON FUNCTION audit_log_prune(integer) FROM PUBLIC;
GRANT EXECUTE ON FUNCTION audit_log_prune(integer) TO superdl_app;
ALTER DEFAULT PRIVILEGES FOR ROLE superdl IN SCHEMA public
  GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO superdl_app;
ALTER DEFAULT PRIVILEGES FOR ROLE superdl IN SCHEMA public
  GRANT USAGE, SELECT, UPDATE ON SEQUENCES TO superdl_app;
